export const blogPosts = [
  // ── 2026 ──────────────────────────────────────────────────────────────────
  {
    id: "why-wax-with-wax-me-too",
    title: "Why Wax With Wax Me Too? Inside Utah's Original Waxing-Only Studio",
    category: "Education",
    date: "June 23, 2026",
    excerpt: "Utah's first waxing-only studio since 2007 — six locations, licensed specialists who actually stay, unhurried appointments, and hygiene standards most salons won't talk about. Here's why thousands of Utahns wouldn't trust their wax to anyone else.",
    readTime: "8 min read",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663396807781/PdWBCFNwvifRXuCRZquLwb/why-wax-with-wmt-hero-iT5CLWDo8w7xM8wo6rGM9h.webp",
    slug: "why-wax-with-wax-me-too",
    relatedService: "/services",
    tags: ["waxing studio Utah", "Brazilian wax", "women-owned", "waxing specialists", "Utah waxing", "professional waxing", "wax me too"],
  },
  // ── 2024 ──────────────────────────────────────────────────────────────────
  {
    id: "win-complimentary-bikini-wax-summer",
    title: "Win a Free Bikini Wax — Smooth Just in Time for Summer",
    category: "Promotions",
    date: "April 2, 2024",
    excerpt: "Say goodbye to razor burns and hello to silky-smooth skin this summer. Wax Me Too is giving away a complimentary bikini wax — find out how to enter and why waxing is the ultimate summer upgrade.",
    readTime: "4 min read",
    image: "/manus-storage/win-complimentary-bikini-wax-summer_ca4b1daf_f41eba5f.webp",
    slug: "win-complimentary-bikini-wax-summer",
    relatedService: "/services#bikini",
    tags: ["bikini wax", "summer", "giveaway", "promotions", "smooth skin"],
  },
  {
    id: "st-george-premier-waxing-salon",
    title: "St. George's Premier Waxing Salon | Wax Me Too",
    category: "Locations",
    date: "March 26, 2024",
    excerpt: "From our roots in Draper in 2007 to St. George in 2008, Wax Me Too has been Southern Utah's go-to waxing studio for over 15 years. Discover what makes our St. George location — and our London Brow Company products — truly special.",
    readTime: "5 min read",
    image: "/manus-storage/st-george-premier-waxing-salon_8b2ae849_8bf45e98.webp",
    slug: "st-george-premier-waxing-salon",
    relatedService: "/services#brows",
    tags: ["St. George", "Southern Utah", "waxing salon", "locations", "eyebrow waxing"],
  },
  {
    id: "vacation-waxing-prep-guide",
    title: "How to Prep for Your Winter Escape with Wax Me Too",
    category: "Prep & Care",
    date: "March 19, 2024",
    excerpt: "Sunscreen — check. Sunglasses — check. Razor? Throw that away. Here's everything you need to know about pre-vacation waxing: timing, what to ask your salon, and why a Brazilian wax is the ultimate travel essential.",
    readTime: "6 min read",
    image: "/manus-storage/vacation-waxing-prep-guide_e0015e9f_3d1e4959.webp",
    slug: "vacation-waxing-prep-guide",
    relatedService: "/services#bikini",
    tags: ["vacation prep", "bikini wax", "travel", "pre-vacation", "smooth skin"],
  },
  {
    id: "military-discounts-wax-me-too-layton",
    title: "Military Discounts at Wax Me Too Layton | Saluting Service",
    category: "Community",
    date: "March 12, 2024",
    excerpt: "At our Layton studio near Hill AFB, we proudly offer military discounts as a small token of appreciation for those who serve. Meet Liz — retired Air Force Master Sergeant turned waxing expert — and learn how we honor our military community.",
    readTime: "4 min read",
    image: "/manus-storage/military-discounts-wax-me-too-layton_7bc1bfb0_d949cf74.webp",
    slug: "military-discounts-wax-me-too-layton",
    relatedService: "/services",
    tags: ["military discount", "Layton", "veterans", "promotions", "waxing deals"],
  },
  {
    id: "why-waxing-is-best-hair-removal",
    title: "Why Waxing Is the Best Hair Removal Method",
    category: "Education",
    date: "March 19, 2024",
    excerpt: "In the world of hair removal, waxing stands apart. From longer-lasting results to finer regrowth over time, here's a comprehensive guide to why professional waxing — especially the Brazilian — is the gold standard for smooth skin.",
    readTime: "5 min read",
    image: "/manus-storage/why-waxing-is-best-hair-removal_df097d15_e807a015.webp",
    slug: "why-waxing-is-best-hair-removal",
    relatedService: "/services#brazilian",
    tags: ["hair removal", "waxing vs shaving", "benefits of waxing", "smooth skin", "long-lasting"],
  },
  {
    id: "bridal-waxing-guide",
    title: "Pre-Wedding Waxing: Brows to Toes Bridal Guide",
    category: "Bridal",
    date: "March 14, 2024",
    excerpt: "Your wedding day deserves flawless skin from head to toe. Utah brides trust Wax Me Too for pre-wedding waxing — here's why we recommend starting at least 3 sessions before the big day, and what to expect.",
    readTime: "4 min read",
    image: "/manus-storage/bridal-waxing-guide_1f1f5bae_3fe4d1cf.webp",
    slug: "bridal-waxing-guide",
    relatedService: "/services#bridal",
    tags: ["bridal waxing", "wedding prep", "bride", "full body wax", "bikini wax"],
  },
  {
    id: "south-jordan-waxing-salon-relocation",
    title: "Wax Me Too South Jordan Moves to a Better Space",
    category: "Locations",
    date: "March 5, 2024",
    excerpt: "We're excited to announce our South Jordan studio has moved to a beautiful new location at 3674 W South Jordan Pkwy. Two full treatment rooms, the same expert estheticians, and all the reasons that make Wax Me Too Utah's most trusted waxing studio.",
    readTime: "5 min read",
    image: "/manus-storage/south-jordan-waxing-salon-relocation_5796c9ab_446852ee.webp",
    slug: "south-jordan-waxing-salon-relocation",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "new location", "waxing salon", "Utah County", "relocation"],
  },

  // ── 2020 ──────────────────────────────────────────────────────────────────
  {
    id: "south-jordan-6th-location-opening",
    title: "Why Wax Me Too South Jordan Stands Apart",
    category: "Locations",
    date: "February 8, 2020",
    excerpt: "Our 6th Utah location is open in South Jordan — and it comes with 8 reasons why Wax Me Too is unlike any other waxing salon in the state. Local, female-owned, no memberships, and sinks in every room.",
    readTime: "6 min read",
    image: "/manus-storage/south-jordan-6th-location-opening_70e2cbd8_3aa100ee.webp",
    slug: "south-jordan-6th-location-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "grand opening", "new location", "waxing salon", "Utah"],
  },
  {
    id: "free-bikini-wax-layton-utah",
    title: "Win a Free Bikini Wax in Layton Utah | Wax Me Too",
    category: "Promotions",
    date: "February 6, 2020",
    excerpt: "Did you know Wax Me Too gives away a free bikini wax every week? Our Layton studio at 360 Fort Lane is Utah's premier waxing destination — here's how to enter and what makes our Layton team exceptional.",
    readTime: "4 min read",
    image: "/manus-storage/free-bikini-wax-layton-utah_d0f6d546_2136b848.webp",
    slug: "free-bikini-wax-layton-utah",
    relatedService: "/services#bikini",
    tags: ["free wax", "Layton", "bikini wax", "promotions", "giveaway"],
  },
  {
    id: "wax-me-too-difference-local-salon",
    title: "Why Wax Me Too Beats Every Chain in Utah",
    category: "Education",
    date: "February 5, 2020",
    excerpt: "What separates Wax Me Too from every other waxing salon in Utah? We're local, women-owned, never franchise-backed, and we've never raised our prices. Here's everything that makes us Utah's first and most trusted waxing-only studio.",
    readTime: "5 min read",
    image: "/manus-storage/wax-me-too-difference-local-salon_fec5b7c1_aee916f2.webp",
    slug: "wax-me-too-difference-local-salon",
    relatedService: "/services",
    tags: ["local salon", "women-owned", "Utah waxing", "professional waxing", "quality"],
  },

  // ── 2019 ──────────────────────────────────────────────────────────────────
  {
    id: "summer-waxing-utah-guide",
    title: "Summer Waxing in Utah: Stay Smooth All Season",
    category: "Prep & Care",
    date: "July 17, 2019",
    excerpt: "Bikinis, lake days, and poolside lounging — summer in Utah is the best reason to ditch the razor for good. Here's everything you need to know about summer waxing, from Brazilian to full leg, at Wax Me Too's 6 Utah locations.",
    readTime: "5 min read",
    image: "/manus-storage/summer-waxing-utah-guide_e8a3fccb_83bf3370.webp",
    slug: "summer-waxing-utah-guide",
    relatedService: "/services#bikini",
    tags: ["summer waxing", "Utah", "bikini season", "smooth skin", "waxing tips"],
  },
  {
    id: "first-brazilian-wax-step-by-step",
    title: "Your First Brazilian Wax at Wax Me Too: What to Know",
    category: "Education",
    date: "February 8, 2019",
    excerpt: "Nervous about your first Brazilian wax? We walk you through every step — from the consent form to the cleanup — so you know exactly what to expect at one of our 6 Utah studios. Spoiler: it's easier than you think.",
    readTime: "7 min read",
    image: "/manus-storage/first-brazilian-wax-step-by-step_e43e9809_1f163ee0.webp",
    slug: "first-brazilian-wax-step-by-step",
    relatedService: "/services#brazilian",
    tags: ["first Brazilian wax", "Brazilian wax", "what to expect", "new clients", "waxing guide"],
  },

  // ── 2017 ──────────────────────────────────────────────────────────────────
  {
    id: "spring-adventure-waxing-utah",
    title: "Get Waxed and Ready for Utah's Outdoor Season",
    category: "Lifestyle",
    date: "March 19, 2017",
    excerpt: "Utah's spring and summer are made for adventure — hiking, camping, lake days, and everything in between. Here's why waxing is the smartest prep move before any outdoor adventure, and how monthly waxing creates finer, softer regrowth over time.",
    readTime: "4 min read",
    image: "/manus-storage/spring-adventure-waxing-utah_68fa0467_eaebf242.webp",
    slug: "spring-adventure-waxing-utah",
    relatedService: "/services#bikini",
    tags: ["spring waxing", "Utah", "outdoor activities", "bikini wax", "smooth skin"],
  },
  {
    id: "south-jordan-waxing-grand-opening",
    title: "Wax Me Too South Jordan: Utah's 6th Waxing Studio",
    category: "Locations",
    date: "March 6, 2017",
    excerpt: "South Jordan, Utah — we've arrived! Wax Me Too's 6th location is now open at South Jordan Parkway, bringing the state's most trusted Brazilian waxing experience to the southwest valley. No memberships, no pressure, just great waxes.",
    readTime: "4 min read",
    image: "/manus-storage/south-jordan-waxing-grand-opening_08fb9ea9_8a054110.webp",
    slug: "south-jordan-waxing-grand-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "grand opening", "waxing salon", "new location", "Utah County"],
  },
  {
    id: "waxing-south-jordan-utah-opening",
    title: "South Jordan Waxing: What to Know Before Your Visit",
    category: "Locations",
    date: "March 1, 2017",
    excerpt: "Wax Me Too is opening its doors in South Jordan at the busy crossroads of South Jordan Parkway and Bangerter. Here's everything new clients need to know — including how to prep for a Brazilian wax and why we're different from every other salon.",
    readTime: "5 min read",
    image: "/manus-storage/waxing-south-jordan-utah-opening_a018a521_566d5603.webp",
    slug: "waxing-south-jordan-utah-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "waxing", "new salon", "Utah", "opening"],
  },
  {
    id: "valentines-day-waxing-rippp-and-swear",
    title: "Valentine's Day Waxing at Wax Me Too | Ripp & Swear",
    category: "Lifestyle",
    date: "February 7, 2017",
    excerpt: "Valentine's Day is the most popular waxing week of the year — and for good reason. Whether you're getting your brows shaped for the big proposal or going full Brazilian for your special evening, Wax Me Too has you covered.",
    readTime: "4 min read",
    image: "/manus-storage/valentines-day-waxing-rippp-and-swear_ef2ed6c5_457f840f.webp",
    slug: "valentines-day-waxing-rippp-and-swear",
    relatedService: "/services#brows",
    tags: ["Valentine's Day", "Brazilian wax", "gift ideas", "couples", "waxing humor"],
  },
  {
    id: "valentines-day-free-wax-giveaway-2017",
    title: "Win a Free Wax — Best Valentine's Day Gift Ever",
    category: "Promotions",
    date: "January 31, 2017",
    excerpt: "What's the perfect Valentine's Day gift — unisex, intimate, and genuinely useful? A Brazilian wax. Enter our weekly free wax drawing and treat yourself (or your partner) to the smoothest Valentine's Day ever.",
    readTime: "3 min read",
    image: "/manus-storage/valentines-day-free-wax-giveaway-2017_faadc184_05ea2ab5.webp",
    slug: "valentines-day-free-wax-giveaway-2017",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "free wax", "giveaway", "promotions", "bikini wax"],
  },
  {
    id: "sundance-film-festival-waxing-utah",
    title: "Sundance Film Festival & Brazilian Waxing in Utah",
    category: "Lifestyle",
    date: "January 25, 2017",
    excerpt: "Every January, Hollywood comes to Utah for Sundance — and our phone rings off the hook. Whether you're a local heading to Park City or a visitor from LA, here's why waxing is the ultimate pre-Sundance prep ritual.",
    readTime: "4 min read",
    image: "/manus-storage/sundance-film-festival-waxing-utah_41dbbf52_078150fb.webp",
    slug: "sundance-film-festival-waxing-utah",
    relatedService: "/services#brazilian",
    tags: ["Sundance", "Park City", "Utah events", "waxing", "celebrity"],
  },

  // ── 2016 ──────────────────────────────────────────────────────────────────
  {
    id: "layton-waxing-salon-new-team",
    title: "Layton Ladies Love Brazilian Waxing at Wax Me Too",
    category: "Locations",
    date: "December 16, 2016",
    excerpt: "Our Layton studio at 360 Fort Lane has grown to 5 licensed estheticians and 3 full treatment rooms — and the reviews are in. Over 289 five-star ratings and counting. Here's what makes our Layton team the best in Davis County.",
    readTime: "4 min read",
    image: "/manus-storage/layton-waxing-salon-new-team_7806f34f_6b905555.webp",
    slug: "layton-waxing-salon-new-team",
    relatedService: "/services#brazilian",
    tags: ["Layton", "estheticians", "waxing team", "professional waxing", "staff"],
  },
  {
    id: "pre-vacation-waxing-checklist",
    title: "Pre-Vacation Waxing Checklist Before the Beach",
    category: "Prep & Care",
    date: "December 14, 2016",
    excerpt: "Heading somewhere warm this winter? Your vacation prep list isn't complete without a wax. Here's the exact timing, what to expect, and why waxing beats shaving every time when you're packing for the beach.",
    readTime: "5 min read",
    image: "/manus-storage/pre-vacation-waxing-checklist_05d92514_673de85c.webp",
    slug: "pre-vacation-waxing-checklist",
    relatedService: "/services#bikini",
    tags: ["vacation prep", "waxing checklist", "travel tips", "bikini wax", "smooth skin"],
  },
  {
    id: "free-bikini-wax-drawing-utah",
    title: "Are You a Winner? Enter Wax Me Too's Free Bikini Wax Drawing",
    category: "Promotions",
    date: "December 8, 2016",
    excerpt: "Every week, Wax Me Too gives away a free bikini wax to one lucky winner across our 5 Utah locations. Here's how to enter — and why thousands of Utah women trust us for their monthly waxing routine.",
    readTime: "3 min read",
    image: "/manus-storage/free-bikini-wax-drawing-utah_974c96de_20cefef7.webp",
    slug: "free-bikini-wax-drawing-utah",
    relatedService: "/services#bikini",
    tags: ["free wax", "bikini wax", "giveaway", "promotions", "Utah"],
  },
  {
    id: "holiday-waxing-on-top-of-the-world",
    title: "Holiday Waxing at Wax Me Too | On Top of the World",
    category: "Lifestyle",
    date: "November 30, 2016",
    excerpt: "The holidays are hectic — but a 15-minute Brazilian wax can make even the most exhausted mom feel amazing. Here's why self-care during the holiday season matters, and how Wax Me Too makes it easy.",
    readTime: "4 min read",
    image: "/manus-storage/holiday-waxing-on-top-of-the-world_d8559707_ce4e663d.webp",
    slug: "holiday-waxing-on-top-of-the-world",
    relatedService: "/services#brazilian",
    tags: ["holiday waxing", "gift ideas", "smooth skin", "winter waxing", "Utah"],
  },
  {
    id: "3-worst-things-waxing-salon",
    title: "3 Red Flags in a Waxing Salon — What to Look For",
    category: "Education",
    date: "November 18, 2016",
    excerpt: "A dirty sink. A messy workstation. An unhappy esthetician. These are the three biggest red flags in any waxing salon — and why Wax Me Too's strict sanitation standards have made us Utah's most trusted waxing studio since 2007.",
    readTime: "5 min read",
    image: "/manus-storage/3-worst-things-waxing-salon_8c92d8c0_af6b4185.webp",
    slug: "3-worst-things-waxing-salon",
    relatedService: "/services",
    tags: ["waxing tips", "salon advice", "what to avoid", "professional waxing", "education"],
  },
  {
    id: "underarm-waxing-guide-utah",
    title: "Everything You Need to Know About Underarm Waxing",
    category: "Education",
    date: "November 15, 2016",
    excerpt: "Underarm waxing is one of the most underrated services at Wax Me Too. It takes just 10 minutes, lasts 3–4 weeks, and leaves your underarms smoother than any razor ever could. Here's exactly what to expect.",
    readTime: "4 min read",
    image: "/manus-storage/underarm-waxing-guide-utah_406dd9cb_c0e0d797.webp",
    slug: "underarm-waxing-guide-utah",
    relatedService: "/services#body",
    tags: ["underarm waxing", "armpit wax", "hair removal", "smooth skin", "waxing guide"],
  },
  {
    id: "throw-away-your-razor",
    title: "7 Reasons to Switch from Shaving to Waxing Today",
    category: "Education",
    date: "November 11, 2016",
    excerpt: "Razor burn, stubble, nicks, and hair that grows back thicker — shaving is the worst. Here are 7 compelling reasons to throw away your razor and switch to professional waxing at Wax Me Too.",
    readTime: "4 min read",
    image: "/manus-storage/throw-away-your-razor_6670313d_247478b5.webp",
    slug: "throw-away-your-razor",
    relatedService: "/services#legs",
    tags: ["waxing vs shaving", "razor bumps", "smooth skin", "hair removal", "benefits of waxing"],
  },
  {
    id: "bikini-wax-types-explained",
    title: "Brazilian vs. Deep Bikini vs. Bikini Wax: Which?",
    category: "Education",
    date: "November 3, 2016",
    excerpt: "Not sure which bikini wax to book? We break down the differences between a Brazilian, Deep Bikini, and standard Bikini wax — so you can walk into your appointment knowing exactly what you want.",
    readTime: "5 min read",
    image: "/manus-storage/bikini-wax-types-explained_237e94a4_00504472.webp",
    slug: "bikini-wax-types-explained",
    relatedService: "/services#bikini",
    tags: ["bikini wax types", "Brazilian wax", "bikini line", "full bikini", "waxing guide"],
  },
  {
    id: "naked-and-afraid-first-brazilian",
    title: "The Real Truth About Getting Your First Brazilian Wax",
    category: "Education",
    date: "November 1, 2016",
    excerpt: "Being naked in front of a stranger, the pain, the embarrassing positions — these are the fears that keep first-timers away from their first Brazilian wax. Here's the honest truth about all of them, from Wax Me Too's expert estheticians.",
    readTime: "6 min read",
    image: "/manus-storage/naked-and-afraid-first-brazilian_c8e576e3_22eeb9b1.webp",
    slug: "naked-and-afraid-first-brazilian",
    relatedService: "/services#brazilian",
    tags: ["first Brazilian wax", "what to expect", "new clients", "Brazilian wax", "waxing humor"],
  },
  {
    id: "mens-eyebrow-waxing-metrosexual",
    title: "Men's Eyebrow Waxing: Why Guys Love Wax Me Too",
    category: "Men's Waxing",
    date: "October 17, 2016",
    excerpt: "The unibrow is out. A clean, masculine brow shape is in. Men's waxing — from brow grooming to the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's everything men need to know before their first appointment.",
    readTime: "5 min read",
    image: "/manus-storage/mens-eyebrow-waxing-metrosexual_37b45201_24ef34e0.webp",
    slug: "mens-eyebrow-waxing-metrosexual",
    relatedService: "/services#mens",
    tags: ["men's waxing", "eyebrow waxing", "male grooming", "metrosexual", "brow shaping"],
  },
  {
    id: "eyebrow-design-waxing-guide",
    title: "Eyebrow Design: Get the Best Brows of Your Life",
    category: "Education",
    date: "October 1, 2016",
    excerpt: "At Wax Me Too, we don't just wax brows — we design them. From consultation to tweezers to tiny scissors, here's the full process behind our eyebrow design service and why clients drive from across Utah for their brow appointments.",
    readTime: "5 min read",
    image: "/manus-storage/eyebrow-design-waxing-guide_556af8e7_9308d8c0.webp",
    slug: "eyebrow-design-waxing-guide",
    relatedService: "/services#brows",
    tags: ["eyebrow waxing", "brow shaping", "eyebrow design", "facial waxing", "beauty tips"],
  },
  {
    id: "hair-removal-layton-utah",
    title: "Hair Removal in Layton Utah | Meet the Wax Me Too Team",
    category: "Locations",
    date: "September 28, 2016",
    excerpt: "Our Layton studio has grown from a one-woman operation to a full team of 5 licensed waxing specialists in a beautiful stand-alone space just off Layton Parkway. Here's why North Utah County clients make Wax Me Too their monthly destination.",
    readTime: "4 min read",
    image: "/manus-storage/hair-removal-layton-utah_abbaa7ae_c806cd33.webp",
    slug: "hair-removal-layton-utah",
    relatedService: "/services#brazilian",
    tags: ["Layton", "hair removal", "waxing", "Utah", "professional waxing"],
  },
  {
    id: "brazilian-waxing-salon-qa",
    title: "Brazilian Waxing Q&A: Your Top Questions Answered",
    category: "Education",
    date: "October 19, 2016",
    excerpt: "How do I choose the right waxing salon? What should I look for in a treatment room? How do I prepare for my first Brazilian? We answer the most common questions we hear from new clients at Wax Me Too.",
    readTime: "6 min read",
    image: "/manus-storage/brazilian-waxing-salon-qa_7e1bea09_4493a33a.webp",
    slug: "brazilian-waxing-salon-qa",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "FAQ", "waxing questions", "what to expect", "waxing guide"],
  },

  // ── 2015 ──────────────────────────────────────────────────────────────────
  {
    id: "prevention-magazine-bikini-wax-tips",
    title: "Prevention Magazine: 9 Tips for the Perfect Bikini Wax",
    category: "Press",
    date: "March 28, 2015",
    excerpt: "Prevention Magazine called us — one of America's leading health and beauty publications — to get our expert tips on getting the perfect bikini wax. Here's what co-founder Jolie Arsenault shared with millions of readers.",
    readTime: "5 min read",
    image: "/manus-storage/prevention-magazine-bikini-wax-tips_c1d4f117_6bf0408f.webp",
    slug: "prevention-magazine-bikini-wax-tips",
    relatedService: "/services#bikini",
    tags: ["bikini wax tips", "Prevention magazine", "waxing advice", "expert tips", "smooth skin"],
  },
  {
    id: "layton-waxing-milly-speaks-spanish",
    title: "Brazilian Waxing in Layton with Milly | Habla Español",
    category: "Locations",
    date: "March 4, 2015",
    excerpt: "Meet Milly — our newest Layton esthetician with 20 years of experience, originally from Venezuela, and fluent in Spanish. Wax Me Too Layton is proud to serve our Spanish-speaking community at our beautiful new 360 Fort Lane location.",
    readTime: "4 min read",
    image: "/manus-storage/layton-waxing-milly-speaks-spanish_5b07ed71_b15379ff.webp",
    slug: "layton-waxing-milly-speaks-spanish",
    relatedService: "/services#brazilian",
    tags: ["Layton", "bilingual", "Spanish-speaking", "esthetician", "inclusive"],
  },
  {
    id: "valentines-day-brazilian-wax-gift",
    title: "Brazilian Wax: The Ultimate Valentine's Day Gift",
    category: "Lifestyle",
    date: "January 26, 2015",
    excerpt: "Looking for a Valentine's Day gift that's unisex, intimate, and genuinely useful? The Brazilian wax is the answer. Here's why thousands of Utah couples make Wax Me Too their Valentine's Day tradition — and how to prepare.",
    readTime: "5 min read",
    image: "/manus-storage/valentines-day-brazilian-wax-gift_a38a70db_7ed868d7.webp",
    slug: "valentines-day-brazilian-wax-gift",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "gift ideas", "Brazilian wax", "couples", "promotions"],
  },
  {
    id: "layton-waxing-salon-new-location",
    title: "Wax Me Too Layton Moves to Fort Lane Plaza",
    category: "Locations",
    date: "January 10, 2015",
    excerpt: "After 4 years of outgrowing our old space, Wax Me Too Layton has moved to a stunning new studio at 360 Fort Lane. Fresh paint, new flooring, sinks in every room, and the same expert team you've trusted for years.",
    readTime: "5 min read",
    image: "/manus-storage/layton-waxing-salon-new-location_c8ca5255_e3188e67.webp",
    slug: "layton-waxing-salon-new-location",
    relatedService: "/services#brazilian",
    tags: ["Layton", "new location", "waxing salon", "Davis County", "Utah"],
  },

  // ── 2013 ──────────────────────────────────────────────────────────────────
  {
    id: "15-minute-brazilian-wax-experience",
    title: "The 15-Minute Brazilian Wax Inside Wax Me Too",
    category: "Education",
    date: "November 7, 2013",
    excerpt: "Fifteen minutes. That's all it takes for a complete Brazilian wax at Wax Me Too. Here's a candid, behind-the-scenes look at what really happens during your appointment — and why our clients keep coming back every month.",
    readTime: "5 min read",
    image: "/manus-storage/15-minute-brazilian-wax-experience_352a0f9c_58601f82.webp",
    slug: "15-minute-brazilian-wax-experience",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "quick wax", "fast service", "professional waxing", "efficiency"],
  },
  {
    id: "draper-waxing-salon-expansion",
    title: "Wax Me Too Draper Expands: New Treatment Room Opens",
    category: "Locations",
    date: "July 31, 2013",
    excerpt: "Due to overwhelming demand, our Draper studio inside Image Studios has opened its fourth treatment room. Owner Joann Gibb shares what drives the summer surge in waxing appointments — and why once clients start, they rarely stop.",
    readTime: "4 min read",
    image: "/manus-storage/draper-waxing-salon-expansion_24f01152_720856cd.webp",
    slug: "draper-waxing-salon-expansion",
    relatedService: "/services#brazilian",
    tags: ["Draper", "expansion", "new location", "waxing salon", "Salt Lake County"],
  },
  {
    id: "salt-lake-city-waxing-salon",
    title: "Brazilian Waxing in Salt Lake City | Wax Me Too",
    category: "Locations",
    date: "April 5, 2013",
    excerpt: "Our downtown Salt Lake City studio is one of our busiest — and for good reason. 3 treatment rooms, 7 expert waxers, and hours from early morning to late evening. Here's what makes our SLC location the go-to for waxing in the city.",
    readTime: "5 min read",
    image: "/manus-storage/salt-lake-city-waxing-salon_3274d330_3da062f5.webp",
    slug: "salt-lake-city-waxing-salon",
    relatedService: "/services#brazilian",
    tags: ["Salt Lake City", "waxing salon", "Utah", "professional waxing", "locations"],
  },
  {
    id: "valentines-day-free-brazilian-2013",
    title: "Win a Free Brazilian Wax for Valentine's Day 2013",
    category: "Promotions",
    date: "January 28, 2013",
    excerpt: "In honor of Valentine's Day 2013, Wax Me Too is giving away a free Brazilian wax to one lucky winner. Here's how to enter — and why the Brazilian wax is the most romantic gift you can give (or receive) this February.",
    readTime: "4 min read",
    image: "/manus-storage/valentines-day-free-brazilian-2013_33420318_5ae4922b.webp",
    slug: "valentines-day-free-brazilian-2013",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "free Brazilian wax", "giveaway", "promotions", "2013"],
  },

  // ── 2012 ──────────────────────────────────────────────────────────────────
  {
    id: "utah-waxing-salon-established-2007",
    title: "Utah's First Waxing-Only Salon: The Story Behind Wax Me Too",
    category: "About",
    date: "December 15, 2012",
    excerpt: "In 2007, two best friends saw a gap in Utah's beauty market and opened the state's first waxing-only salon. Here's the story of how Wax Me Too was born, what drives our philosophy, and why we've grown to 6 locations across Utah.",
    readTime: "6 min read",
    image: "/manus-storage/utah-waxing-salon-established-2007_e27f4942_1e586b97.webp",
    slug: "utah-waxing-salon-established-2007",
    relatedService: "/services",
    tags: ["Utah waxing", "established 2007", "women-owned", "waxing history", "professional waxing"],
  },
  {
    id: "brazilian-wax-benefits-vs-shaving",
    title: "Brazilian Wax vs. Shaving: Why Waxing Wins Every Time",
    category: "Education",
    date: "November 10, 2012",
    excerpt: "Shaving leaves stubble, ingrown hairs, and razor burn. Waxing removes hair from the root, leaving skin smooth for weeks and causing hair to grow back finer over time. Here's the complete comparison — and why Wax Me Too clients never go back to shaving.",
    readTime: "5 min read",
    image: "/manus-storage/brazilian-wax-benefits-vs-shaving_ef031f28_10ddc813.webp",
    slug: "brazilian-wax-benefits-vs-shaving",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "waxing vs shaving", "benefits", "smooth skin", "hair removal"],
  },
  {
    id: "waxing-while-pregnant-utah",
    title: "Can You Wax While Pregnant? What Moms Need to Know",
    category: "Education",
    date: "October 5, 2012",
    excerpt: "Yes, you can wax while pregnant — with a few important considerations. Our licensed estheticians at Wax Me Too have helped hundreds of expecting moms stay smooth and comfortable throughout their pregnancies. Here's what you need to know.",
    readTime: "5 min read",
    image: "/manus-storage/waxing-while-pregnant-utah_83fcb842_a503ba5b.webp",
    slug: "waxing-while-pregnant-utah",
    relatedService: "/services#brazilian",
    tags: ["waxing while pregnant", "pregnancy waxing", "safe waxing", "prenatal care", "sensitive skin"],
  },
  {
    id: "ingrown-hair-prevention-waxing",
    title: "Ingrown Hairs After Waxing: How to Prevent Them",
    category: "Prep & Care",
    date: "September 12, 2012",
    excerpt: "Ingrown hairs are one of the most common concerns after waxing — but they're largely preventable. Here's our expert guide to exfoliation, moisturizing, and aftercare that keeps skin smooth and bump-free between appointments.",
    readTime: "5 min read",
    image: "/manus-storage/ingrown-hair-prevention-waxing_16bd891d_fab552da.webp",
    slug: "ingrown-hair-prevention-waxing",
    relatedService: "/after-care",
    tags: ["ingrown hairs", "ingrown hair prevention", "aftercare", "smooth skin", "waxing tips"],
  },
  {
    id: "waxing-sensitive-skin-guide",
    title: "Waxing with Sensitive Skin: Tips from Our Experts",
    category: "Education",
    date: "August 20, 2012",
    excerpt: "Sensitive skin doesn't have to mean painful waxing. Our estheticians use fragrance-free honey wax and gentle techniques specifically designed for reactive skin types. Here's how we make waxing comfortable for everyone.",
    readTime: "4 min read",
    image: "/manus-storage/waxing-sensitive-skin-guide_09488b95_949ab19a.webp",
    slug: "waxing-sensitive-skin-guide",
    relatedService: "/services#brazilian",
    tags: ["sensitive skin", "waxing tips", "skin care", "gentle waxing", "aftercare"],
  },
  {
    id: "how-often-should-you-wax",
    title: "How Often Should You Wax? Complete Frequency Guide",
    category: "Education",
    date: "July 15, 2012",
    excerpt: "Most clients wax every 4 weeks — but the right frequency depends on your hair growth cycle, the area being waxed, and your personal preference. Here's the complete guide from Wax Me Too's licensed estheticians.",
    readTime: "5 min read",
    image: "/manus-storage/how-often-should-you-wax_b3f20f61_78e69379.webp",
    slug: "how-often-should-you-wax",
    relatedService: "/services",
    tags: ["waxing schedule", "how often to wax", "waxing frequency", "hair regrowth", "waxing tips"],
  },
  {
    id: "waxing-for-men-manzilian-guide",
    title: "Men's Waxing Guide: Everything About the Manzilian",
    category: "Men's Waxing",
    date: "June 10, 2012",
    excerpt: "Men's waxing — especially the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's a complete guide for men considering their first appointment: what to expect, how to prepare, and why it's worth it.",
    readTime: "6 min read",
    image: "/manus-storage/waxing-for-men-manzilian-guide_12927fe1_f7890036.webp",
    slug: "waxing-for-men-manzilian-guide",
    relatedService: "/services#mens",
    tags: ["men's waxing", "Manzilian", "male Brazilian wax", "male grooming", "body waxing"],
  },
  {
    id: "st-george-waxing-salon-utah",
    title: "Waxing in St. George Utah: Wax Me Too's Southern Utah Studio",
    category: "Locations",
    date: "May 5, 2012",
    excerpt: "Wax Me Too's St. George studio was our second location ever — and it's been serving Southern Utah and Mesquite, Nevada clients since 2008. Here's what makes our St. George team special and why clients drive from across Washington County to see us.",
    readTime: "4 min read",
    image: "/manus-storage/st-george-waxing-salon-utah_597ea654_10d60b6e.webp",
    slug: "st-george-waxing-salon-utah",
    relatedService: "/services#brazilian",
    tags: ["St. George", "Southern Utah", "waxing salon", "Washington County", "locations"],
  },
  {
    id: "waxing-aftercare-guide",
    title: "Waxing Aftercare: Complete Guide to Post-Wax Skin Care",
    category: "Prep & Care",
    date: "April 2, 2012",
    excerpt: "What you do in the 24–48 hours after your wax matters as much as the wax itself. Here's the complete aftercare guide from Wax Me Too — covering what to avoid, how to moisturize, and how to prevent ingrown hairs.",
    readTime: "5 min read",
    image: "/manus-storage/waxing-aftercare-guide_f980cdd4_098ceccb.webp",
    slug: "waxing-aftercare-guide",
    relatedService: "/after-care",
    tags: ["aftercare", "post-wax care", "ingrown hairs", "smooth skin", "waxing tips"],
  },
  {
    id: "waxing-before-care-guide",
    title: "How to Prepare for Your Wax: The Complete Before-Care Guide",
    category: "Prep & Care",
    date: "March 15, 2012",
    excerpt: "The secret to a great wax starts before you even walk in the door. Here's everything you need to do — and avoid — in the days leading up to your appointment to ensure the smoothest, most complete wax possible.",
    readTime: "4 min read",
    image: "/manus-storage/waxing-before-care-guide_6f2ce957_ccfc850d.webp",
    slug: "waxing-before-care-guide",
    relatedService: "/before-care",
    tags: ["before care", "pre-wax prep", "waxing tips", "first wax", "preparation"],
  },
  {
    id: "wax-me-too-happy-faces-community",
    title: "How Wax Me Too Gives Back to Utah's Youth",
    category: "Community",
    date: "February 20, 2012",
    excerpt: "Our Happy Faces program donates free brow and lip waxing to middle and high school students who need a confidence boost. Here's the story behind the program and why giving back to Utah's youth is at the heart of everything we do at Wax Me Too.",
    readTime: "4 min read",
    image: "/manus-storage/wax-me-too-happy-faces-community_0614881f_06bbbddf.webp",
    slug: "wax-me-too-happy-faces-community",
    relatedService: "/about",
    tags: ["community", "client stories", "Utah waxing", "women-owned", "testimonials"],
  },
  {
    id: "waxing-faq-utah",
    title: "Waxing FAQ: Your Top Questions About Professional Waxing",
    category: "Education",
    date: "January 10, 2012",
    excerpt: "Can you wax during your period? How long does hair need to be? Does waxing hurt less over time? We answer the 20 most common questions we hear from new and returning clients at Wax Me Too's Utah studios.",
    readTime: "7 min read",
    image: "/manus-storage/waxing-faq-utah_95555afc_6a9f2825.webp",
    slug: "waxing-faq-utah",
    relatedService: "/faq",
    tags: ["FAQ", "waxing questions", "Utah waxing", "what to expect", "waxing guide"],
  },
];

