export const blogPosts = [
  // ── 2024 ──────────────────────────────────────────────────────────────────
  {
    id: "win-complimentary-bikini-wax-summer",
    title: "Win a Complimentary Bikini Wax — Be Smooth and Groovin' Just in Time for Summer!",
    category: "Promotions",
    date: "April 2, 2024",
    excerpt: "Say goodbye to razor burns and hello to silky-smooth skin this summer. Wax Me Too is giving away a complimentary bikini wax — find out how to enter and why waxing is the ultimate summer upgrade.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    slug: "win-complimentary-bikini-wax-summer",
    relatedService: "/services#bikini",
    tags: ["bikini wax", "summer", "giveaway", "promotions", "smooth skin"],
  },
  {
    id: "st-george-premier-waxing-salon",
    title: "Waxing Wonderland: Unveiling St. George's Premier Waxing Salon",
    category: "Locations",
    date: "March 26, 2024",
    excerpt: "From our roots in Draper in 2007 to St. George in 2008, Wax Me Too has been Southern Utah's go-to waxing studio for over 15 years. Discover what makes our St. George location — and our London Brow Company products — truly special.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&q=80",
    slug: "st-george-premier-waxing-salon",
    relatedService: "/services#brows",
    tags: ["St. George", "Southern Utah", "waxing salon", "locations", "eyebrow waxing"],
  },
  {
    id: "vacation-waxing-prep-guide",
    title: "Vacation Baby! How to Prepare for Your Winter Escape with Wax Me Too",
    category: "Prep & Care",
    date: "March 19, 2024",
    excerpt: "Sunscreen — check. Sunglasses — check. Razor? Throw that away. Here's everything you need to know about pre-vacation waxing: timing, what to ask your salon, and why a Brazilian wax is the ultimate travel essential.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&q=80",
    slug: "vacation-waxing-prep-guide",
    relatedService: "/services#bikini",
    tags: ["vacation prep", "bikini wax", "travel", "pre-vacation", "smooth skin"],
  },
  {
    id: "military-discounts-wax-me-too-layton",
    title: "Saluting Service: Honoring Our Military with Discounts at Wax Me Too Layton",
    category: "Community",
    date: "March 12, 2024",
    excerpt: "At our Layton studio near Hill AFB, we proudly offer military discounts as a small token of appreciation for those who serve. Meet Liz — retired Air Force Master Sergeant turned waxing expert — and learn how we honor our military community.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "military-discounts-wax-me-too-layton",
    relatedService: "/services",
    tags: ["military discount", "Layton", "veterans", "promotions", "waxing deals"],
  },
  {
    id: "why-waxing-is-best-hair-removal",
    title: "Smooth Silhouettes: Why Waxing Is the Best Hair Removal Method",
    category: "Education",
    date: "March 19, 2024",
    excerpt: "In the world of hair removal, waxing stands apart. From longer-lasting results to finer regrowth over time, here's a comprehensive guide to why professional waxing — especially the Brazilian — is the gold standard for smooth skin.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "why-waxing-is-best-hair-removal",
    relatedService: "/services#brazilian",
    tags: ["hair removal", "waxing vs shaving", "benefits of waxing", "smooth skin", "long-lasting"],
  },
  {
    id: "bridal-waxing-guide",
    title: "A Bridal Must-Do: The Importance of Pre-Wedding Waxing from Brows to Toes",
    category: "Bridal",
    date: "March 14, 2024",
    excerpt: "Your wedding day deserves flawless skin from head to toe. Utah brides trust Wax Me Too for pre-wedding waxing — here's why we recommend starting at least 3 sessions before the big day, and what to expect.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "bridal-waxing-guide",
    relatedService: "/services#bridal",
    tags: ["bridal waxing", "wedding prep", "bride", "full body wax", "bikini wax"],
  },
  {
    id: "south-jordan-waxing-salon-relocation",
    title: "Smooth Moves: Wax Me Too South Jordan Relocates to a Better Space",
    category: "Locations",
    date: "March 5, 2024",
    excerpt: "We're excited to announce our South Jordan studio has moved to a beautiful new location at 3674 W South Jordan Pkwy. Two full treatment rooms, the same expert estheticians, and all the reasons that make Wax Me Too Utah's most trusted waxing studio.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80",
    slug: "south-jordan-waxing-salon-relocation",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "new location", "waxing salon", "Utah County", "relocation"],
  },

  // ── 2020 ──────────────────────────────────────────────────────────────────
  {
    id: "south-jordan-6th-location-opening",
    title: "Why Wax Me Too South Jordan Is Different from Every Other Waxing Salon",
    category: "Locations",
    date: "February 8, 2020",
    excerpt: "Our 6th Utah location is open in South Jordan — and it comes with 8 reasons why Wax Me Too is unlike any other waxing salon in the state. Local, female-owned, no memberships, and sinks in every room.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=600&q=80",
    slug: "south-jordan-6th-location-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "grand opening", "new location", "waxing salon", "Utah"],
  },
  {
    id: "free-bikini-wax-layton-utah",
    title: "Waxing in Layton Utah: Enter to Win a Free Bikini Wax at Wax Me Too",
    category: "Promotions",
    date: "February 6, 2020",
    excerpt: "Did you know Wax Me Too gives away a free bikini wax every week? Our Layton studio at 360 Fort Lane is Utah's premier waxing destination — here's how to enter and what makes our Layton team exceptional.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1530053969600-caed2596d242?w=600&q=80",
    slug: "free-bikini-wax-layton-utah",
    relatedService: "/services#bikini",
    tags: ["free wax", "Layton", "bikini wax", "promotions", "giveaway"],
  },
  {
    id: "wax-me-too-difference-local-salon",
    title: "The Wax Me Too Difference: Why Utah's Local Waxing Studio Beats Every Chain",
    category: "Education",
    date: "February 5, 2020",
    excerpt: "What separates Wax Me Too from every other waxing salon in Utah? We're local, women-owned, never franchise-backed, and we've never raised our prices. Here's everything that makes us Utah's first and most trusted waxing-only studio.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1607008829749-c0f284a49fc4?w=600&q=80",
    slug: "wax-me-too-difference-local-salon",
    relatedService: "/services",
    tags: ["local salon", "women-owned", "Utah waxing", "professional waxing", "quality"],
  },

  // ── 2019 ──────────────────────────────────────────────────────────────────
  {
    id: "summer-waxing-utah-guide",
    title: "Summer Waxing in Utah: Your Complete Guide to Staying Smooth All Season",
    category: "Prep & Care",
    date: "July 17, 2019",
    excerpt: "Bikinis, lake days, and poolside lounging — summer in Utah is the best reason to ditch the razor for good. Here's everything you need to know about summer waxing, from Brazilian to full leg, at Wax Me Too's 6 Utah locations.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80",
    slug: "summer-waxing-utah-guide",
    relatedService: "/services#bikini",
    tags: ["summer waxing", "Utah", "bikini season", "smooth skin", "waxing tips"],
  },
  {
    id: "first-brazilian-wax-step-by-step",
    title: "Everything You Need to Know Before Your First Brazilian Wax at Wax Me Too",
    category: "Education",
    date: "February 8, 2019",
    excerpt: "Nervous about your first Brazilian wax? We walk you through every step — from the consent form to the cleanup — so you know exactly what to expect at one of our 6 Utah studios. Spoiler: it's easier than you think.",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1621798553012-c7a9f3e5d4b2?w=600&q=80",
    slug: "first-brazilian-wax-step-by-step",
    relatedService: "/services#brazilian",
    tags: ["first Brazilian wax", "Brazilian wax", "what to expect", "new clients", "waxing guide"],
  },

  // ── 2017 ──────────────────────────────────────────────────────────────────
  {
    id: "spring-adventure-waxing-utah",
    title: "Adventure's Calling: Get Waxed and Ready for Utah's Best Outdoor Season",
    category: "Lifestyle",
    date: "March 19, 2017",
    excerpt: "Utah's spring and summer are made for adventure — hiking, camping, lake days, and everything in between. Here's why waxing is the smartest prep move before any outdoor adventure, and how monthly waxing creates finer, softer regrowth over time.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80",
    slug: "spring-adventure-waxing-utah",
    relatedService: "/services#bikini",
    tags: ["spring waxing", "Utah", "outdoor activities", "bikini wax", "smooth skin"],
  },
  {
    id: "south-jordan-waxing-grand-opening",
    title: "Wax Me Too Opens in South Jordan: Utah's 6th Waxing-Only Studio Is Here",
    category: "Locations",
    date: "March 6, 2017",
    excerpt: "South Jordan, Utah — we've arrived! Wax Me Too's 6th location is now open at South Jordan Parkway, bringing the state's most trusted Brazilian waxing experience to the southwest valley. No memberships, no pressure, just great waxes.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80",
    slug: "south-jordan-waxing-grand-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "grand opening", "waxing salon", "new location", "Utah County"],
  },
  {
    id: "waxing-south-jordan-utah-opening",
    title: "Waxing in South Jordan Utah: What to Know Before Your First Appointment",
    category: "Locations",
    date: "March 1, 2017",
    excerpt: "Wax Me Too is opening its doors in South Jordan at the busy crossroads of South Jordan Parkway and Bangerter. Here's everything new clients need to know — including how to prep for a Brazilian wax and why we're different from every other salon.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80",
    slug: "waxing-south-jordan-utah-opening",
    relatedService: "/services#brazilian",
    tags: ["South Jordan", "waxing", "new salon", "Utah", "opening"],
  },
  {
    id: "valentines-day-waxing-rippp-and-swear",
    title: "Ripp & Swear: The Things We Do for Love — Valentine's Day Waxing at Wax Me Too",
    category: "Lifestyle",
    date: "February 7, 2017",
    excerpt: "Valentine's Day is the most popular waxing week of the year — and for good reason. Whether you're getting your brows shaped for the big proposal or going full Brazilian for your special evening, Wax Me Too has you covered.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
    slug: "valentines-day-waxing-rippp-and-swear",
    relatedService: "/services#brows",
    tags: ["Valentine's Day", "Brazilian wax", "gift ideas", "couples", "waxing humor"],
  },
  {
    id: "valentines-day-free-wax-giveaway-2017",
    title: "The Best Valentine's Day Gift Ever: Win a Free Wax at Wax Me Too",
    category: "Promotions",
    date: "January 31, 2017",
    excerpt: "What's the perfect Valentine's Day gift — unisex, intimate, and genuinely useful? A Brazilian wax. Enter our weekly free wax drawing and treat yourself (or your partner) to the smoothest Valentine's Day ever.",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=600&q=80",
    slug: "valentines-day-free-wax-giveaway-2017",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "free wax", "giveaway", "promotions", "bikini wax"],
  },
  {
    id: "sundance-film-festival-waxing-utah",
    title: "Utah Snowbunnies, Sundance Film Festival & Brazilian Waxing: How They All Connect",
    category: "Lifestyle",
    date: "January 25, 2017",
    excerpt: "Every January, Hollywood comes to Utah for Sundance — and our phone rings off the hook. Whether you're a local heading to Park City or a visitor from LA, here's why waxing is the ultimate pre-Sundance prep ritual.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80",
    slug: "sundance-film-festival-waxing-utah",
    relatedService: "/services#brazilian",
    tags: ["Sundance", "Park City", "Utah events", "waxing", "celebrity"],
  },

  // ── 2016 ──────────────────────────────────────────────────────────────────
  {
    id: "layton-waxing-salon-new-team",
    title: "New! Layton Ladies Go Crazy Over Brazilian Waxing at Wax Me Too",
    category: "Locations",
    date: "December 16, 2016",
    excerpt: "Our Layton studio at 360 Fort Lane has grown to 5 licensed estheticians and 3 full treatment rooms — and the reviews are in. Over 289 five-star ratings and counting. Here's what makes our Layton team the best in Davis County.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&q=80",
    slug: "layton-waxing-salon-new-team",
    relatedService: "/services#brazilian",
    tags: ["Layton", "estheticians", "waxing team", "professional waxing", "staff"],
  },
  {
    id: "pre-vacation-waxing-checklist",
    title: "Don't Hit the Beach Without This Pre-Vacation Waxing Checklist",
    category: "Prep & Care",
    date: "December 14, 2016",
    excerpt: "Heading somewhere warm this winter? Your vacation prep list isn't complete without a wax. Here's the exact timing, what to expect, and why waxing beats shaving every time when you're packing for the beach.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&q=80",
    slug: "pre-vacation-waxing-checklist",
    relatedService: "/services#bikini",
    tags: ["vacation prep", "waxing checklist", "travel tips", "bikini wax", "smooth skin"],
  },
  {
    id: "free-bikini-wax-drawing-utah",
    title: "Are You a Winner? Enter Wax Me Too's Free Bikini Wax Drawing",
    category: "Promotions",
    date: "December 8, 2016",
    excerpt: "Every week, Wax Me Too gives away a free bikini wax to one lucky winner across our 5 Utah locations. Here's how to enter — and why thousands of Utah women trust us for their monthly waxing routine.",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&q=80",
    slug: "free-bikini-wax-drawing-utah",
    relatedService: "/services#bikini",
    tags: ["free wax", "bikini wax", "giveaway", "promotions", "Utah"],
  },
  {
    id: "holiday-waxing-on-top-of-the-world",
    title: "On Top of the World Because of Some Lady Bits: Holiday Waxing at Wax Me Too",
    category: "Lifestyle",
    date: "November 30, 2016",
    excerpt: "The holidays are hectic — but a 15-minute Brazilian wax can make even the most exhausted mom feel amazing. Here's why self-care during the holiday season matters, and how Wax Me Too makes it easy.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80",
    slug: "holiday-waxing-on-top-of-the-world",
    relatedService: "/services#brazilian",
    tags: ["holiday waxing", "gift ideas", "smooth skin", "winter waxing", "Utah"],
  },
  {
    id: "3-worst-things-waxing-salon",
    title: "The 3 Worst Things You Can See in a Waxing Salon (And What to Look For Instead)",
    category: "Education",
    date: "November 18, 2016",
    excerpt: "A dirty sink. A messy workstation. An unhappy esthetician. These are the three biggest red flags in any waxing salon — and why Wax Me Too's strict sanitation standards have made us Utah's most trusted waxing studio since 2007.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1583416750470-965b2707b355?w=600&q=80",
    slug: "3-worst-things-waxing-salon",
    relatedService: "/services",
    tags: ["waxing tips", "salon advice", "what to avoid", "professional waxing", "education"],
  },
  {
    id: "underarm-waxing-guide-utah",
    title: "Harry Pitts: Everything You Need to Know About Underarm Waxing",
    category: "Education",
    date: "November 15, 2016",
    excerpt: "Underarm waxing is one of the most underrated services at Wax Me Too. It takes just 10 minutes, lasts 3–4 weeks, and leaves your underarms smoother than any razor ever could. Here's exactly what to expect.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=600&q=80",
    slug: "underarm-waxing-guide-utah",
    relatedService: "/services#body",
    tags: ["underarm waxing", "armpit wax", "hair removal", "smooth skin", "waxing guide"],
  },
  {
    id: "throw-away-your-razor",
    title: "Throw That Sucker Away: 7 Reasons to Switch from Shaving to Waxing Today",
    category: "Education",
    date: "November 11, 2016",
    excerpt: "Razor burn, stubble, nicks, and hair that grows back thicker — shaving is the worst. Here are 7 compelling reasons to throw away your razor and switch to professional waxing at Wax Me Too.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
    slug: "throw-away-your-razor",
    relatedService: "/services#legs",
    tags: ["waxing vs shaving", "razor bumps", "smooth skin", "hair removal", "benefits of waxing"],
  },
  {
    id: "bikini-wax-types-explained",
    title: "Brazilian vs. Deep Bikini vs. Bikini Wax: Which One Is Right for You?",
    category: "Education",
    date: "November 3, 2016",
    excerpt: "Not sure which bikini wax to book? We break down the differences between a Brazilian, Deep Bikini, and standard Bikini wax — so you can walk into your appointment knowing exactly what you want.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&q=80",
    slug: "bikini-wax-types-explained",
    relatedService: "/services#bikini",
    tags: ["bikini wax types", "Brazilian wax", "bikini line", "full bikini", "waxing guide"],
  },
  {
    id: "naked-and-afraid-first-brazilian",
    title: "Naked and Afraid: The Real Truth About Getting Your First Brazilian Wax",
    category: "Education",
    date: "November 1, 2016",
    excerpt: "Being naked in front of a stranger, the pain, the embarrassing positions — these are the fears that keep first-timers away from their first Brazilian wax. Here's the honest truth about all of them, from Wax Me Too's expert estheticians.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80",
    slug: "naked-and-afraid-first-brazilian",
    relatedService: "/services#brazilian",
    tags: ["first Brazilian wax", "what to expect", "new clients", "Brazilian wax", "waxing humor"],
  },
  {
    id: "mens-eyebrow-waxing-metrosexual",
    title: "The Metrosexual Male and Eyebrow Waxing: Why Men Are Flocking to Wax Me Too",
    category: "Men's Waxing",
    date: "October 17, 2016",
    excerpt: "The unibrow is out. A clean, masculine brow shape is in. Men's waxing — from brow grooming to the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's everything men need to know before their first appointment.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1518895312237-a9e23508077d?w=600&q=80",
    slug: "mens-eyebrow-waxing-metrosexual",
    relatedService: "/services#mens",
    tags: ["men's waxing", "eyebrow waxing", "male grooming", "metrosexual", "brow shaping"],
  },
  {
    id: "eyebrow-design-waxing-guide",
    title: "Eyebrow Design: How to Get the Best Brows of Your Life at Wax Me Too",
    category: "Education",
    date: "October 1, 2016",
    excerpt: "At Wax Me Too, we don't just wax brows — we design them. From consultation to tweezers to tiny scissors, here's the full process behind our eyebrow design service and why clients drive from across Utah for their brow appointments.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
    slug: "eyebrow-design-waxing-guide",
    relatedService: "/services#brows",
    tags: ["eyebrow waxing", "brow shaping", "eyebrow design", "facial waxing", "beauty tips"],
  },
  {
    id: "hair-removal-layton-utah",
    title: "Hair Removal in Layton Utah: Meet the Wax Me Too Team at 360 Fort Lane",
    category: "Locations",
    date: "September 28, 2016",
    excerpt: "Our Layton studio has grown from a one-woman operation to a full team of 5 licensed waxing specialists in a beautiful stand-alone space just off Layton Parkway. Here's why North Utah County clients make Wax Me Too their monthly destination.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=600&q=80",
    slug: "hair-removal-layton-utah",
    relatedService: "/services#brazilian",
    tags: ["Layton", "hair removal", "waxing", "Utah", "professional waxing"],
  },
  {
    id: "brazilian-waxing-salon-qa",
    title: "Brazilian Waxing Salon Q&A: Your Most Common Questions Answered",
    category: "Education",
    date: "October 19, 2016",
    excerpt: "How do I choose the right waxing salon? What should I look for in a treatment room? How do I prepare for my first Brazilian? We answer the most common questions we hear from new clients at Wax Me Too.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80",
    slug: "brazilian-waxing-salon-qa",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "FAQ", "waxing questions", "what to expect", "waxing guide"],
  },

  // ── 2015 ──────────────────────────────────────────────────────────────────
  {
    id: "prevention-magazine-bikini-wax-tips",
    title: "Wax Me Too Featured in Prevention Magazine: 9 Tips for the Perfect Bikini Wax",
    category: "Press",
    date: "March 28, 2015",
    excerpt: "Prevention Magazine called us — one of America's leading health and beauty publications — to get our expert tips on getting the perfect bikini wax. Here's what co-founder Jolie Arsenault shared with millions of readers.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1551524164-687a55dd1126?w=600&q=80",
    slug: "prevention-magazine-bikini-wax-tips",
    relatedService: "/services#bikini",
    tags: ["bikini wax tips", "Prevention magazine", "waxing advice", "expert tips", "smooth skin"],
  },
  {
    id: "layton-waxing-milly-speaks-spanish",
    title: "Brazilian Waxing in Layton Utah with Milly — Ella Habla Español",
    category: "Locations",
    date: "March 4, 2015",
    excerpt: "Meet Milly — our newest Layton esthetician with 20 years of experience, originally from Venezuela, and fluent in Spanish. Wax Me Too Layton is proud to serve our Spanish-speaking community at our beautiful new 360 Fort Lane location.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80",
    slug: "layton-waxing-milly-speaks-spanish",
    relatedService: "/services#brazilian",
    tags: ["Layton", "bilingual", "Spanish-speaking", "esthetician", "inclusive"],
  },
  {
    id: "valentines-day-brazilian-wax-gift",
    title: "The Perfect Valentine's Day Gift: Why a Brazilian Wax Is the Ultimate Romantic Treat",
    category: "Lifestyle",
    date: "January 26, 2015",
    excerpt: "Looking for a Valentine's Day gift that's unisex, intimate, and genuinely useful? The Brazilian wax is the answer. Here's why thousands of Utah couples make Wax Me Too their Valentine's Day tradition — and how to prepare.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=600&q=80",
    slug: "valentines-day-brazilian-wax-gift",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "gift ideas", "Brazilian wax", "couples", "promotions"],
  },
  {
    id: "layton-waxing-salon-new-location",
    title: "Wax Me Too Layton Has Moved to a Beautiful New Salon at Fort Lane Plaza",
    category: "Locations",
    date: "January 10, 2015",
    excerpt: "After 4 years of outgrowing our old space, Wax Me Too Layton has moved to a stunning new studio at 360 Fort Lane. Fresh paint, new flooring, sinks in every room, and the same expert team you've trusted for years.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=600&q=80",
    slug: "layton-waxing-salon-new-location",
    relatedService: "/services#brazilian",
    tags: ["Layton", "new location", "waxing salon", "Davis County", "Utah"],
  },

  // ── 2013 ──────────────────────────────────────────────────────────────────
  {
    id: "15-minute-brazilian-wax-experience",
    title: "The 15-Minute Brazilian Wax: What Really Happens Inside a Wax Me Too Studio",
    category: "Education",
    date: "November 7, 2013",
    excerpt: "Fifteen minutes. That's all it takes for a complete Brazilian wax at Wax Me Too. Here's a candid, behind-the-scenes look at what really happens during your appointment — and why our clients keep coming back every month.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=600&q=80",
    slug: "15-minute-brazilian-wax-experience",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "quick wax", "fast service", "professional waxing", "efficiency"],
  },
  {
    id: "draper-waxing-salon-expansion",
    title: "Wax Me Too Draper Expands: A Fourth Treatment Room Opens Due to High Demand",
    category: "Locations",
    date: "July 31, 2013",
    excerpt: "Due to overwhelming demand, our Draper studio inside Image Studios has opened its fourth treatment room. Owner Joann Gibb shares what drives the summer surge in waxing appointments — and why once clients start, they rarely stop.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "draper-waxing-salon-expansion",
    relatedService: "/services#brazilian",
    tags: ["Draper", "expansion", "new location", "waxing salon", "Salt Lake County"],
  },
  {
    id: "salt-lake-city-waxing-salon",
    title: "Brazilian Waxing in Salt Lake City: Inside Wax Me Too's Downtown Studio",
    category: "Locations",
    date: "April 5, 2013",
    excerpt: "Our downtown Salt Lake City studio is one of our busiest — and for good reason. 3 treatment rooms, 7 expert waxers, and hours from early morning to late evening. Here's what makes our SLC location the go-to for waxing in the city.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "salt-lake-city-waxing-salon",
    relatedService: "/services#brazilian",
    tags: ["Salt Lake City", "waxing salon", "Utah", "professional waxing", "locations"],
  },
  {
    id: "valentines-day-free-brazilian-2013",
    title: "Win a Free Brazilian Wax for Valentine's Day 2013 at Wax Me Too",
    category: "Promotions",
    date: "January 28, 2013",
    excerpt: "In honor of Valentine's Day 2013, Wax Me Too is giving away a free Brazilian wax to one lucky winner. Here's how to enter — and why the Brazilian wax is the most romantic gift you can give (or receive) this February.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1500840216050-6ffa99d75160?w=600&q=80",
    slug: "valentines-day-free-brazilian-2013",
    relatedService: "/services#brazilian",
    tags: ["Valentine's Day", "free Brazilian wax", "giveaway", "promotions", "2013"],
  },

  // ── 2012 ──────────────────────────────────────────────────────────────────
  {
    id: "utah-waxing-salon-established-2007",
    title: "Utah's First Waxing-Only Salon: The Story Behind Wax Me Too",
    category: "About",
    date: "December 15, 2012",
    excerpt: "In 2007, two best friends saw a gap in Utah's beauty market and opened the state's first waxing-only salon. Here's the story of how Wax Me Too was born, what drives our philosophy, and why we've grown to 6 locations across Utah.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80",
    slug: "utah-waxing-salon-established-2007",
    relatedService: "/services",
    tags: ["Utah waxing", "established 2007", "women-owned", "waxing history", "professional waxing"],
  },
  {
    id: "brazilian-wax-benefits-vs-shaving",
    title: "Brazilian Wax vs. Shaving: Why Waxing Wins Every Time",
    category: "Education",
    date: "November 10, 2012",
    excerpt: "Shaving leaves stubble, ingrown hairs, and razor burn. Waxing removes hair from the root, leaving skin smooth for weeks and causing hair to grow back finer over time. Here's the complete comparison — and why Wax Me Too clients never go back to shaving.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1559599101-f09722fb4948?w=600&q=80",
    slug: "brazilian-wax-benefits-vs-shaving",
    relatedService: "/services#brazilian",
    tags: ["Brazilian wax", "waxing vs shaving", "benefits", "smooth skin", "hair removal"],
  },
  {
    id: "waxing-while-pregnant-utah",
    title: "Can You Wax While Pregnant? Everything Expecting Moms Need to Know",
    category: "Education",
    date: "October 5, 2012",
    excerpt: "Yes, you can wax while pregnant — with a few important considerations. Our licensed estheticians at Wax Me Too have helped hundreds of expecting moms stay smooth and comfortable throughout their pregnancies. Here's what you need to know.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1533681904393-9ab6eee7e408?w=600&q=80",
    slug: "waxing-while-pregnant-utah",
    relatedService: "/services#brazilian",
    tags: ["waxing while pregnant", "pregnancy waxing", "safe waxing", "prenatal care", "sensitive skin"],
  },
  {
    id: "ingrown-hair-prevention-waxing",
    title: "Ingrown Hairs After Waxing: How to Prevent Them and Keep Skin Smooth",
    category: "Prep & Care",
    date: "September 12, 2012",
    excerpt: "Ingrown hairs are one of the most common concerns after waxing — but they're largely preventable. Here's our expert guide to exfoliation, moisturizing, and aftercare that keeps skin smooth and bump-free between appointments.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600&q=80",
    slug: "ingrown-hair-prevention-waxing",
    relatedService: "/after-care",
    tags: ["ingrown hairs", "ingrown hair prevention", "aftercare", "smooth skin", "waxing tips"],
  },
  {
    id: "waxing-sensitive-skin-guide",
    title: "Waxing with Sensitive Skin: Tips from Wax Me Too's Expert Estheticians",
    category: "Education",
    date: "August 20, 2012",
    excerpt: "Sensitive skin doesn't have to mean painful waxing. Our estheticians use fragrance-free honey wax and gentle techniques specifically designed for reactive skin types. Here's how we make waxing comfortable for everyone.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    slug: "waxing-sensitive-skin-guide",
    relatedService: "/services#brazilian",
    tags: ["sensitive skin", "waxing tips", "skin care", "gentle waxing", "aftercare"],
  },
  {
    id: "how-often-should-you-wax",
    title: "How Often Should You Wax? The Complete Guide to Waxing Frequency",
    category: "Education",
    date: "July 15, 2012",
    excerpt: "Most clients wax every 4 weeks — but the right frequency depends on your hair growth cycle, the area being waxed, and your personal preference. Here's the complete guide from Wax Me Too's licensed estheticians.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    slug: "how-often-should-you-wax",
    relatedService: "/services",
    tags: ["waxing schedule", "how often to wax", "waxing frequency", "hair regrowth", "waxing tips"],
  },
  {
    id: "waxing-for-men-manzilian-guide",
    title: "Men's Waxing Guide: Everything You Need to Know About the Manzilian",
    category: "Men's Waxing",
    date: "June 10, 2012",
    excerpt: "Men's waxing — especially the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's a complete guide for men considering their first appointment: what to expect, how to prepare, and why it's worth it.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&q=80",
    slug: "waxing-for-men-manzilian-guide",
    relatedService: "/services#mens",
    tags: ["men's waxing", "Manzilian", "male Brazilian wax", "male grooming", "body waxing"],
  },
  {
    id: "st-george-waxing-salon-utah",
    title: "Waxing in St. George Utah: Wax Me Too's Southern Utah Studio",
    category: "Locations",
    date: "May 5, 2012",
    excerpt: "Wax Me Too's St. George studio was our second location ever — and it's been serving Southern Utah and Mesquite, Nevada clients since 2008. Here's what makes our St. George team special and why clients drive from across Washington County to see us.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=600&q=80",
    slug: "st-george-waxing-salon-utah",
    relatedService: "/services#brazilian",
    tags: ["St. George", "Southern Utah", "waxing salon", "Washington County", "locations"],
  },
  {
    id: "waxing-aftercare-guide",
    title: "Waxing Aftercare: The Complete Guide to Caring for Your Skin After a Wax",
    category: "Prep & Care",
    date: "April 2, 2012",
    excerpt: "What you do in the 24–48 hours after your wax matters as much as the wax itself. Here's the complete aftercare guide from Wax Me Too — covering what to avoid, how to moisturize, and how to prevent ingrown hairs.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1614159689023-2e5f1f6c0e5a?w=600&q=80",
    slug: "waxing-aftercare-guide",
    relatedService: "/after-care",
    tags: ["aftercare", "post-wax care", "ingrown hairs", "smooth skin", "waxing tips"],
  },
  {
    id: "waxing-before-care-guide",
    title: "How to Prepare for Your Wax: The Complete Before-Care Guide",
    category: "Prep & Care",
    date: "March 15, 2012",
    excerpt: "The secret to a great wax starts before you even walk in the door. Here's everything you need to do — and avoid — in the days leading up to your appointment to ensure the smoothest, most complete wax possible.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80",
    slug: "waxing-before-care-guide",
    relatedService: "/before-care",
    tags: ["before care", "pre-wax prep", "waxing tips", "first wax", "preparation"],
  },
  {
    id: "wax-me-too-happy-faces-community",
    title: "Happy Faces: How Wax Me Too Gives Back to Utah's Youth Through Free Waxing",
    category: "Community",
    date: "February 20, 2012",
    excerpt: "Our Happy Faces program donates free brow and lip waxing to middle and high school students who need a confidence boost. Here's the story behind the program and why giving back to Utah's youth is at the heart of everything we do at Wax Me Too.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1509909756405-be0199881695?w=600&q=80",
    slug: "wax-me-too-happy-faces-community",
    relatedService: "/about",
    tags: ["community", "client stories", "Utah waxing", "women-owned", "testimonials"],
  },
  {
    id: "waxing-faq-utah",
    title: "Waxing FAQ: Your Most Common Questions About Professional Waxing Answered",
    category: "Education",
    date: "January 10, 2012",
    excerpt: "Can you wax during your period? How long does hair need to be? Does waxing hurt less over time? We answer the 20 most common questions we hear from new and returning clients at Wax Me Too's Utah studios.",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80",
    slug: "waxing-faq-utah",
    relatedService: "/faq",
    tags: ["FAQ", "waxing questions", "Utah waxing", "what to expect", "waxing guide"],
  },
];

