// WAX ME TOO — Site Data
// All content is original and written for the Wax Me Too brand

export const BOOKING_URL = "https://www.mangomint.com/waxmetoo";

export const locations = [
  {
    id: "provo",
    name: "Provo",
    address: "1234 N University Ave, Provo, UT 84604",
    phone: "(801) 555-0101",
    email: "provo@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=Provo,UT",
    description: "Our flagship Provo studio is conveniently located near BYU campus. Serving Utah County since 2007 with expert waxing in a warm, private setting.",
    city: "Provo",
    county: "Utah County",
    state: "UT",
  },
  {
    id: "orem",
    name: "Orem",
    address: "456 W Center St, Orem, UT 84057",
    phone: "(801) 555-0202",
    email: "orem@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=Orem,UT",
    description: "Our Orem location brings the same boutique waxing experience to the heart of Utah County. Easy parking, private rooms, and expert estheticians.",
    city: "Orem",
    county: "Utah County",
    state: "UT",
  },
  {
    id: "salt-lake-city",
    name: "Salt Lake City",
    address: "789 S State St, Salt Lake City, UT 84111",
    phone: "(801) 555-0303",
    email: "slc@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 6:00 PM",
      "Sunday": "10:00 AM – 4:00 PM",
    },
    mapUrl: "https://maps.google.com/?q=Salt+Lake+City,UT",
    description: "Our Salt Lake City studio is centrally located for easy access from anywhere in the valley. Extended Sunday hours for your convenience.",
    city: "Salt Lake City",
    county: "Salt Lake County",
    state: "UT",
  },
  {
    id: "st-george",
    name: "St. George",
    address: "321 E Tabernacle St, St. George, UT 84770",
    phone: "(435) 555-0404",
    email: "stgeorge@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=St.+George,UT",
    description: "Serving Southern Utah's growing community, our St. George studio offers the full Wax Me Too experience in Washington County's premier city.",
    city: "St. George",
    county: "Washington County",
    state: "UT",
  },
];

export const serviceCategories = [
  {
    id: "womens-waxing",
    name: "Women's Waxing",
    description: "From Brazilian to brows, our women's waxing menu covers every inch with precision and care.",
    icon: "✦",
    services: [
      {
        id: "brazilian",
        name: "Brazilian Wax",
        tagline: "Our signature service. Complete, clean, confident.",
        description: "The Brazilian wax removes all or nearly all hair from the bikini area — front, back, and everything in between. Our estheticians are trained to make this service as comfortable as possible, using premium hard wax that grips the hair, not the skin.",
        whoItsFor: "Anyone who wants a clean, smooth result with long-lasting confidence. First-timers are always welcome — we'll walk you through every step.",
        prep: "Let hair grow to at least ¼ inch (about 3–4 weeks of growth). Exfoliate 24 hours before. Avoid scheduling during your period if possible.",
        aftercare: "Avoid heat, friction, and tight clothing for 24–48 hours. Exfoliate gently after 48 hours to prevent ingrown hairs.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–45 min",
        popular: true,
      },
      {
        id: "bikini",
        name: "Bikini Wax",
        tagline: "Clean lines, effortless confidence.",
        description: "A classic bikini wax removes hair along the bikini line — everything that would show in a swimsuit. Clean, precise, and quick.",
        whoItsFor: "Perfect for those who prefer a natural look with clean edges, or as a starting point before trying a Brazilian.",
        prep: "Hair should be at least ¼ inch long. Avoid sun exposure on the area for 24 hours before.",
        aftercare: "Keep the area clean and moisturized. Avoid tight underwear for 24 hours.",
        priceCash: 35,
        priceCard: 37,
        duration: "20–30 min",
        popular: true,
      },
      {
        id: "deep-bikini",
        name: "Deep Bikini Wax",
        tagline: "More coverage, more confidence.",
        description: "The deep bikini wax goes further than a standard bikini — removing more hair from the front and sides while leaving a small strip or triangle. The perfect middle ground between bikini and Brazilian.",
        whoItsFor: "Great for those who want more coverage removed than a standard bikini but aren't ready for a full Brazilian.",
        prep: "Same as Brazilian — ¼ inch minimum hair growth.",
        aftercare: "Avoid heat and friction for 24 hours. Moisturize daily.",
        priceCash: 45,
        priceCard: 47,
        duration: "25–35 min",
        popular: true,
      },
      {
        id: "full-leg",
        name: "Full Leg Wax",
        tagline: "Silky smooth from hip to toe.",
        description: "Our full leg wax covers everything from the upper thigh down to the ankle, leaving your legs smooth and touchably soft for weeks.",
        whoItsFor: "Anyone who wants to ditch the razor and enjoy weeks of smooth, hair-free legs.",
        prep: "Hair should be at least ¼ inch. Exfoliate the day before for best results.",
        aftercare: "Moisturize daily. Avoid sun exposure for 24 hours.",
        priceCash: 65,
        priceCard: 68,
        duration: "45–60 min",
        popular: true,
      },
      {
        id: "half-leg",
        name: "Half Leg Wax",
        tagline: "Lower leg or upper leg — your choice.",
        description: "Target just the lower leg (knee to ankle) or upper leg (hip to knee). A great option for maintaining smooth legs between full leg appointments.",
        priceCash: 38,
        priceCard: 40,
        duration: "25–35 min",
      },
      {
        id: "underarm",
        name: "Underarm Wax",
        tagline: "Smooth underarms that last for weeks.",
        description: "Quick, effective, and longer-lasting than shaving. Our underarm wax leaves skin smooth and reduces regrowth over time with regular appointments.",
        whoItsFor: "Anyone tired of daily shaving or razor irritation.",
        prep: "Hair should be at least ¼ inch. Avoid deodorant on the day of your appointment.",
        aftercare: "Avoid deodorant for 24 hours. Apply a gentle, fragrance-free moisturizer.",
        priceCash: 20,
        priceCard: 21,
        duration: "15 min",
        popular: true,
      },
      {
        id: "full-arm",
        name: "Full Arm Wax",
        tagline: "Smooth arms, effortlessly.",
        description: "Removes hair from the wrist to the shoulder for a clean, smooth finish that lasts 3–6 weeks.",
        priceCash: 45,
        priceCard: 47,
        duration: "30–40 min",
      },
      {
        id: "half-arm",
        name: "Half Arm Wax",
        tagline: "Lower or upper arm waxing.",
        description: "Target the lower arm (wrist to elbow) or upper arm (elbow to shoulder).",
        priceCash: 28,
        priceCard: 30,
        duration: "20 min",
      },
      {
        id: "stomach",
        name: "Stomach Wax",
        tagline: "Clean lines for a smooth midsection.",
        description: "Removes hair from the stomach area, including the happy trail and navel area.",
        priceCash: 25,
        priceCard: 26,
        duration: "20 min",
      },
      {
        id: "back",
        name: "Back Wax",
        tagline: "Full back, clean results.",
        description: "Complete back waxing for a smooth, clean finish. Available for all genders.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–40 min",
      },
    ],
  },
  {
    id: "mens-waxing",
    name: "Men's Waxing",
    description: "Clean, professional waxing services designed for men. No judgment, just results.",
    icon: "◆",
    services: [
      {
        id: "mens-back",
        name: "Men's Back Wax",
        tagline: "Clean back, confident you.",
        description: "Professional back waxing for men. Our estheticians are experienced and discreet — this is a completely normal service and we treat it as such.",
        priceCash: 60,
        priceCard: 63,
        duration: "30–40 min",
      },
      {
        id: "mens-chest",
        name: "Men's Chest Wax",
        tagline: "Smooth chest, lasting results.",
        description: "Full chest waxing for a clean, defined look. Longer-lasting than shaving with less irritation over time.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–40 min",
      },
      {
        id: "mens-back-chest",
        name: "Men's Back & Chest Wax",
        tagline: "The complete package.",
        description: "Combine back and chest waxing in one appointment for maximum convenience and savings.",
        priceCash: 105,
        priceCard: 110,
        duration: "60–75 min",
      },
      {
        id: "mens-brow",
        name: "Men's Brow Wax",
        tagline: "Groomed brows, clean look.",
        description: "Clean up the brow line and remove unwanted hair between the brows for a polished, natural look.",
        priceCash: 18,
        priceCard: 19,
        duration: "15 min",
      },
      {
        id: "mens-nose",
        name: "Men's Nose Wax",
        tagline: "Quick, clean, effective.",
        description: "Safe, quick nose wax that removes visible nasal hair. One of our most popular men's services.",
        priceCash: 15,
        priceCard: 16,
        duration: "10 min",
      },
      {
        id: "mens-ear",
        name: "Men's Ear Wax",
        tagline: "Discreet and effective.",
        description: "Removes unwanted ear hair quickly and cleanly.",
        priceCash: 15,
        priceCard: 16,
        duration: "10 min",
      },
    ],
  },
  {
    id: "face",
    name: "Face Waxing",
    description: "Precise facial waxing for perfectly shaped brows, clean upper lips, and smooth skin.",
    icon: "◇",
    services: [
      {
        id: "brow-wax",
        name: "Brow Wax",
        tagline: "Your best brows. Every time.",
        description: "Our brow wax shapes, defines, and cleans up your brows for a polished, natural look. Our estheticians work with your natural brow shape to enhance — never over-thin.",
        whoItsFor: "Anyone who wants clean, defined brows without the guesswork of at-home tweezing.",
        prep: "Come in with your natural brows — no need to shape them beforehand.",
        aftercare: "Avoid touching the area. Apply a gentle moisturizer if needed. Avoid sun exposure for 24 hours.",
        priceCash: 18,
        priceCard: 19,
        duration: "15–20 min",
        popular: true,
      },
      {
        id: "brow-tint",
        name: "Brow Wax + Tint",
        tagline: "Shape and color in one appointment.",
        description: "Combine a precise brow wax with a professional tint to add depth, definition, and fullness to your brows.",
        priceCash: 35,
        priceCard: 37,
        duration: "30 min",
        popular: true,
      },
      {
        id: "upper-lip",
        name: "Upper Lip Wax",
        tagline: "Quick, clean, and effective.",
        description: "A fast, precise upper lip wax that removes unwanted hair and leaves skin smooth. One of our most popular quick services.",
        priceCash: 12,
        priceCard: 13,
        duration: "10 min",
        popular: true,
      },
      {
        id: "chin",
        name: "Chin Wax",
        tagline: "Clean chin, smooth confidence.",
        description: "Removes unwanted chin hair for a clean, smooth finish.",
        priceCash: 12,
        priceCard: 13,
        duration: "10 min",
      },
      {
        id: "full-face",
        name: "Full Face Wax",
        tagline: "Complete facial waxing in one visit.",
        description: "Includes brows, upper lip, chin, cheeks, and sideburns. The complete facial waxing experience.",
        priceCash: 55,
        priceCard: 58,
        duration: "40–50 min",
      },
      {
        id: "cheeks-sideburns",
        name: "Cheeks & Sideburns",
        tagline: "Clean sides, polished look.",
        description: "Removes peach fuzz and unwanted hair from the cheeks and sideburn area.",
        priceCash: 18,
        priceCard: 19,
        duration: "15 min",
      },
    ],
  },
  {
    id: "tinting",
    name: "Tinting",
    description: "Professional brow and lash tinting to enhance your natural features.",
    icon: "◈",
    services: [
      {
        id: "lash-tint",
        name: "Lash Tint",
        tagline: "Defined lashes without the mascara.",
        description: "Professional lash tinting adds depth and definition to your natural lashes. Wake up with beautiful lashes every day.",
        priceCash: 28,
        priceCard: 30,
        duration: "20–25 min",
      },
      {
        id: "brow-tint-only",
        name: "Brow Tint",
        tagline: "Fuller, defined brows.",
        description: "Professional brow tinting to add color, depth, and definition. Great for sparse or light brows.",
        priceCash: 20,
        priceCard: 21,
        duration: "15–20 min",
      },
      {
        id: "lash-brow-tint",
        name: "Lash + Brow Tint",
        tagline: "Complete eye definition.",
        description: "Combine lash and brow tinting in one appointment for a complete, polished eye look.",
        priceCash: 45,
        priceCard: 47,
        duration: "35–40 min",
      },
    ],
  },
];

export const faqs = [
  {
    id: 1,
    category: "First Visit",
    question: "I've never been waxed before. What should I expect?",
    answer: "Welcome! First-time waxing is completely normal, and our estheticians are experienced at making new clients feel at ease. You'll be taken to a private room, given a moment to prepare, and your esthetician will walk you through every step before they begin. Most clients are surprised by how manageable the experience is — especially when they return regularly.",
  },
  {
    id: 2,
    category: "First Visit",
    question: "Is it embarrassing to get a Brazilian wax?",
    answer: "Not at all — and we hear this question often. Our estheticians are licensed professionals who perform these services every day. To them, it's simply their craft. You'll be treated with complete respect and discretion. Many clients who were nervous before their first visit become regulars because of how comfortable the experience actually is.",
  },
  {
    id: 3,
    category: "Preparation",
    question: "How long does my hair need to be?",
    answer: "Hair should be at least ¼ inch long — roughly 3–4 weeks of growth after shaving. If it's too short, the wax won't grip properly. If it's longer than ½ inch, we may trim it before waxing. When in doubt, let it grow a bit more than you think you need.",
  },
  {
    id: 4,
    category: "Preparation",
    question: "Should I do anything to prepare for my appointment?",
    answer: "Yes! Gently exfoliate the area 24–48 hours before your appointment to remove dead skin cells. Avoid applying lotion or oils on the day of your appointment. Wear comfortable, loose-fitting clothing. For bikini/Brazilian services, avoid scheduling during your menstrual cycle if possible, as sensitivity is heightened.",
  },
  {
    id: 5,
    category: "Pain & Comfort",
    question: "Does waxing hurt?",
    answer: "There is some discomfort — we won't pretend otherwise. But most clients describe it as a quick, sharp sensation that passes immediately. The good news: it gets significantly easier with each visit as hair grows back finer and sparser. Regular clients often say their appointments feel much more comfortable than their first experience.",
  },
  {
    id: 6,
    category: "Pain & Comfort",
    question: "How can I reduce discomfort?",
    answer: "Take an over-the-counter pain reliever (like ibuprofen) 30–45 minutes before your appointment. Avoid caffeine on the day of your visit. Make sure your skin is clean and dry. Breathe steadily during the service — our estheticians will often guide your breathing. And remember: it gets easier every time.",
  },
  {
    id: 7,
    category: "Aftercare",
    question: "What should I do after my wax?",
    answer: "For the first 24–48 hours: avoid hot showers, saunas, and steam rooms; skip tight clothing; avoid sun exposure on waxed areas; and hold off on exercise that causes heavy sweating. After 48 hours, begin gentle exfoliation 2–3 times per week to prevent ingrown hairs. Moisturize daily with a fragrance-free lotion.",
  },
  {
    id: 8,
    category: "Aftercare",
    question: "How do I prevent ingrown hairs?",
    answer: "Regular exfoliation is the key. Starting 48 hours after your wax, gently exfoliate the waxed area 2–3 times per week using a soft scrub or exfoliating mitt. Moisturize daily. Wearing loose, breathable clothing also helps. With regular waxing appointments, ingrown hairs typically become less of an issue over time.",
  },
  {
    id: 9,
    category: "Results",
    question: "How long will my results last?",
    answer: "Most clients enjoy smooth skin for 3–6 weeks, depending on their individual hair growth cycle. With regular waxing, hair grows back finer and sparser over time, which means longer-lasting results. We recommend booking your next appointment before you leave to maintain your results.",
  },
  {
    id: 10,
    category: "Booking",
    question: "How do I book an appointment?",
    answer: "You can book online through our booking system — just click 'Book Now' and select your location, service, and preferred time. You can also call your nearest location directly. We recommend booking in advance, especially for weekend appointments.",
  },
  {
    id: 11,
    category: "Booking",
    question: "What is your cancellation policy?",
    answer: "We ask for at least 24 hours notice for cancellations or rescheduling. Late cancellations or no-shows may be subject to a fee. We understand that life happens — just reach out as soon as possible and we'll do our best to accommodate you.",
  },
  {
    id: 12,
    category: "Sanitation",
    question: "How do you ensure sanitation and hygiene?",
    answer: "Sanitation is a non-negotiable standard at Wax Me Too. We use fresh, single-use applicators for every client — no double-dipping, ever. Treatment rooms are thoroughly cleaned and sanitized between every appointment. All linens are changed between clients. Our estheticians follow strict hand hygiene protocols. We use eco-friendly, skin-safe wax products.",
  },
  {
    id: 13,
    category: "Pricing",
    question: "Do you charge more for credit cards?",
    answer: "We display both cash and credit card pricing on our menu. The cash price reflects a small discount for clients who pay with cash. Both prices are clearly listed so you can choose what works best for you.",
  },
  {
    id: 14,
    category: "First Visit",
    question: "Do you offer a new client special?",
    answer: "Yes! We offer a special discount for first-time clients. Ask about our current new client offer when you book, or look for the offer on our homepage. It's our way of welcoming you to the Wax Me Too family.",
  },
];

export const blogPosts = [
  {
    id: "brazilian-wax-first-time",
    title: "Your First Brazilian Wax: Everything You Need to Know",
    category: "First Visit",
    date: "March 15, 2025",
    excerpt: "Nervous about your first Brazilian? We break down exactly what to expect, how to prepare, and why so many first-timers become regulars.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "brazilian-wax-first-time",
  },
  {
    id: "ingrown-hair-prevention",
    title: "How to Prevent Ingrown Hairs After Waxing",
    category: "Aftercare",
    date: "February 28, 2025",
    excerpt: "Ingrown hairs are the most common post-wax concern. Here's the simple routine that keeps them from happening.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    slug: "ingrown-hair-prevention",
  },
  {
    id: "how-long-wax-results-last",
    title: "How Long Do Waxing Results Actually Last?",
    category: "Education",
    date: "February 10, 2025",
    excerpt: "The honest answer depends on your hair growth cycle. Here's what to expect and how to maximize your results between appointments.",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80",
    slug: "how-long-wax-results-last",
  },
  {
    id: "waxing-vs-shaving",
    title: "Waxing vs. Shaving: Why Regular Waxers Don't Go Back",
    category: "Education",
    date: "January 22, 2025",
    excerpt: "Once you experience the smoothness and longevity of professional waxing, the razor starts to feel like a downgrade. Here's the real comparison.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "waxing-vs-shaving",
  },
  {
    id: "brow-wax-shape-guide",
    title: "Finding Your Best Brow Shape: A Guide to Brow Waxing",
    category: "Face",
    date: "January 8, 2025",
    excerpt: "Great brows frame your face. Here's how our estheticians approach brow shaping and what you can expect from a professional brow wax.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&q=80",
    slug: "brow-wax-shape-guide",
  },
  {
    id: "waxing-sensitive-skin",
    title: "Waxing with Sensitive Skin: What You Need to Know",
    category: "Prep & Care",
    date: "December 15, 2024",
    excerpt: "Sensitive skin doesn't have to mean skipping waxing. With the right preparation and aftercare, most people with sensitive skin can wax safely.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80",
    slug: "waxing-sensitive-skin",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    location: "Provo, UT",
    rating: 5,
    text: "I was so nervous for my first Brazilian, but my esthetician made me feel completely at ease. She explained everything, was so professional, and the result was amazing. I'm already booked for next month!",
    service: "Brazilian Wax",
  },
  {
    id: 2,
    name: "Jessica T.",
    location: "Salt Lake City, UT",
    rating: 5,
    text: "I've been coming to Wax Me Too for three years and I won't go anywhere else. The consistency is incredible — every esthetician is skilled, the studios are always immaculate, and I always leave feeling great.",
    service: "Regular Client",
  },
  {
    id: 3,
    name: "Amanda R.",
    location: "Orem, UT",
    rating: 5,
    text: "The brow wax here is genuinely the best I've ever had. They work with your natural shape instead of over-thinning, and the results last so much longer than I expected.",
    service: "Brow Wax",
  },
  {
    id: 4,
    name: "Kayla B.",
    location: "St. George, UT",
    rating: 5,
    text: "As someone who was always self-conscious about getting waxed, I cannot say enough about how comfortable this place makes you feel. Zero judgment, total professionalism, and genuinely great results.",
    service: "Brazilian Wax",
  },
  {
    id: 5,
    name: "Michelle L.",
    location: "Provo, UT",
    rating: 5,
    text: "I switched from shaving to waxing two years ago and I'll never go back. The hair grows back so much finer now, and my appointments are quick and easy. The new client offer made it easy to try.",
    service: "Full Leg + Underarm",
  },
  {
    id: 6,
    name: "Taylor H.",
    location: "Salt Lake City, UT",
    rating: 5,
    text: "Brought my sister for her first wax and we both left raving. The studio is beautiful, the staff is warm and knowledgeable, and the pricing is very fair for the quality you get.",
    service: "First Visit",
  },
];

export const trustBadges = [
  { icon: "🌿", label: "Eco-Friendly Products" },
  { icon: "✦", label: "Women-Owned Since 2007" },
  { icon: "🔒", label: "Privacy-First Standards" },
  { icon: "⭐", label: "500+ 5-Star Reviews" },
  { icon: "🧼", label: "Strict Sanitation Protocols" },
  { icon: "💛", label: "No Double-Dipping, Ever" },
];
