// WAX ME TOO — Site Data
// All content is original and written for the Wax Me Too brand

export const BOOKING_URL = "https://www.mangomint.com/waxmetoo";

export const locations = [
  {
    id: "layton",
    name: "Layton",
    address: "360 S Fort Ln #101, Layton, UT 84041",
    phone: "(801) 572-7771",
    email: "layton@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=360+S+Fort+Ln+%23101,+Layton,+UT+84041",
    description: "Our Layton studio serves Davis and Weber County clients with the same premium waxing experience Wax Me Too has delivered since 2007. Military discounts available. Convenient location, private rooms, and expert estheticians.",
    city: "Layton",
    county: "Davis County",
    state: "UT",
    note: "Military Discounts Available",
  },
  {
    id: "south-jordan",
    name: "South Jordan",
    address: "3674 W South Jordan Pkwy, South Jordan, UT 84095",
    phone: "(801) 572-7771",
    email: "southjordan@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=3674+W+South+Jordan+Pkwy,+South+Jordan,+UT+84095",
    description: "Our South Jordan studio brings the full Wax Me Too boutique experience to the southwest valley. Serving Utah County and Salt Lake County clients with easy access and ample parking.",
    city: "South Jordan",
    county: "Salt Lake County",
    state: "UT",
  },
  {
    id: "orem",
    name: "Orem",
    address: "1160 S State St #250, Orem, UT 84097",
    phone: "(801) 572-7771",
    email: "orem@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=1160+S+State+St+%23250,+Orem,+UT+84097",
    description: "Our Orem studio brings the full Wax Me Too boutique experience to Utah County. Easy parking, private rooms, and the expert estheticians you’ve come to trust.",
    city: "Orem",
    county: "Utah County",
    state: "UT",
  },
  {
    id: "salt-lake-city",
    name: "Salt Lake City",
    address: "1850 South 300 West, Suite A (inside Miri Lash Studio), Salt Lake City, UT 84102",
    phone: "(801) 572-7771",
    email: "slc@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=1850+South+300+West,+Salt+Lake+City,+UT+84102",
    description: "Our Salt Lake City studio is located inside Miri Lash Studio, centrally positioned for easy access from anywhere in the valley. Expert estheticians, private rooms, and the same premium Wax Me Too experience.",
    city: "Salt Lake City",
    county: "Salt Lake County",
    state: "UT",
  },
  {
    id: "draper",
    name: "Draper",
    address: "177 West 12300 South, Draper, UT 84020",
    phone: "(801) 572-7771",
    email: "draper@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=177+West+12300+South,+Draper,+UT+84020",
    description: "Our Draper studio serves the south Salt Lake Valley with the same boutique waxing experience Wax Me Too is known for. Convenient freeway access and ample parking.",
    city: "Draper",
    county: "Salt Lake County",
    state: "UT",
  },
  {
    id: "st-george",
    name: "St. George",
    address: "175 W 900 S #9, St. George, UT 84770",
    phone: "(435) 572-7771",
    email: "stgeorge@waxmetoo.com",
    hours: {
      "Mon–Fri": "9:00 AM – 7:00 PM",
      "Saturday": "9:00 AM – 5:00 PM",
      "Sunday": "Closed",
    },
    mapUrl: "https://maps.google.com/?q=175+W+900+S+%239,+St.+George,+UT+84770",
    description: "Serving Washington County and beyond — our St. George studio is the go-to destination for Southern Utah and Mesquite, Nevada clients seeking a premium waxing experience close to home.",
    city: "St. George",
    county: "Washington County",
    state: "UT",
  },
];

export const serviceCategories = [
  {
    id: "womens-waxing",
    name: "Women's Waxing",
    description: "From Brazilian to brows, our women's waxing menu covers every inch with precision and care.",
    icon: "✦",
    services: [
      {
        id: "brazilian",
        name: "Brazilian Wax",
        tagline: "Our signature service. Complete, clean, confident.",
        description: "The Brazilian wax removes all or nearly all hair from the bikini area — front, back, and everything in between. Our estheticians are trained to make this service as comfortable as possible, using premium hard wax that grips the hair, not the skin.",
        whoItsFor: "Anyone who wants a clean, smooth result with long-lasting confidence. First-timers are always welcome — we'll walk you through every step.",
        prep: "Let hair grow to at least ¼ inch (about 3–4 weeks of growth). Exfoliate 24 hours before. Avoid scheduling during your period if possible.",
        aftercare: "Avoid heat, friction, and tight clothing for 24–48 hours. Exfoliate gently after 48 hours to prevent ingrown hairs.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–45 min",
        popular: true,
      },
      {
        id: "bikini",
        name: "Bikini Wax",
        tagline: "Clean lines, effortless confidence.",
        description: "A classic bikini wax removes hair along the bikini line — everything that would show in a swimsuit. Clean, precise, and quick.",
        whoItsFor: "Perfect for those who prefer a natural look with clean edges, or as a starting point before trying a Brazilian.",
        prep: "Hair should be at least ¼ inch long. Avoid sun exposure on the area for 24 hours before.",
        aftercare: "Keep the area clean and moisturized. Avoid tight underwear for 24 hours.",
        priceCash: 35,
        priceCard: 37,
        duration: "20–30 min",
        popular: true,
      },
      {
        id: "deep-bikini",
        name: "Deep Bikini Wax",
        tagline: "More coverage, more confidence.",
        description: "The deep bikini wax goes further than a standard bikini — removing more hair from the front and sides while leaving a small strip or triangle. The perfect middle ground between bikini and Brazilian.",
        whoItsFor: "Great for those who want more coverage removed than a standard bikini but aren't ready for a full Brazilian.",
        prep: "Same as Brazilian — ¼ inch minimum hair growth.",
        aftercare: "Avoid heat and friction for 24 hours. Moisturize daily.",
        priceCash: 45,
        priceCard: 47,
        duration: "25–35 min",
        popular: true,
      },
      {
        id: "full-leg",
        name: "Full Leg Wax",
        tagline: "Silky smooth from hip to toe.",
        description: "Our full leg wax covers everything from the upper thigh down to the ankle, leaving your legs smooth and touchably soft for weeks.",
        whoItsFor: "Anyone who wants to ditch the razor and enjoy weeks of smooth, hair-free legs.",
        prep: "Hair should be at least ¼ inch. Exfoliate the day before for best results.",
        aftercare: "Moisturize daily. Avoid sun exposure for 24 hours.",
        priceCash: 65,
        priceCard: 68,
        duration: "45–60 min",
        popular: true,
      },
      {
        id: "half-leg",
        name: "Half Leg Wax",
        tagline: "Lower leg or upper leg — your choice.",
        description: "Target just the lower leg (knee to ankle) or upper leg (hip to knee). A great option for maintaining smooth legs between full leg appointments.",
        priceCash: 38,
        priceCard: 40,
        duration: "25–35 min",
      },
      {
        id: "underarm",
        name: "Underarm Wax",
        tagline: "Smooth underarms that last for weeks.",
        description: "Quick, effective, and longer-lasting than shaving. Our underarm wax leaves skin smooth and reduces regrowth over time with regular appointments.",
        whoItsFor: "Anyone tired of daily shaving or razor irritation.",
        prep: "Hair should be at least ¼ inch. Avoid deodorant on the day of your appointment.",
        aftercare: "Avoid deodorant for 24 hours. Apply a gentle, fragrance-free moisturizer.",
        priceCash: 20,
        priceCard: 21,
        duration: "15 min",
        popular: true,
      },
      {
        id: "full-arm",
        name: "Full Arm Wax",
        tagline: "Smooth arms, effortlessly.",
        description: "Removes hair from the wrist to the shoulder for a clean, smooth finish that lasts 3–6 weeks.",
        priceCash: 45,
        priceCard: 47,
        duration: "30–40 min",
      },
      {
        id: "half-arm",
        name: "Half Arm Wax",
        tagline: "Lower or upper arm waxing.",
        description: "Target the lower arm (wrist to elbow) or upper arm (elbow to shoulder).",
        priceCash: 28,
        priceCard: 30,
        duration: "20 min",
      },
      {
        id: "stomach",
        name: "Stomach Wax",
        tagline: "Clean lines for a smooth midsection.",
        description: "Removes hair from the stomach area, including the happy trail and navel area.",
        priceCash: 25,
        priceCard: 26,
        duration: "20 min",
      },
      {
        id: "back",
        name: "Back Wax",
        tagline: "Full back, clean results.",
        description: "Complete back waxing for a smooth, clean finish. Available for all genders.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–40 min",
      },
    ],
  },
  {
    id: "mens-waxing",
    name: "Men's Waxing",
    description: "Clean, professional waxing services designed for men. No judgment, just results.",
    icon: "◆",
    services: [
      {
        id: "mens-back",
        name: "Men's Back Wax",
        tagline: "Clean back, confident you.",
        description: "Professional back waxing for men. Our estheticians are experienced and discreet — this is a completely normal service and we treat it as such.",
        priceCash: 60,
        priceCard: 63,
        duration: "30–40 min",
      },
      {
        id: "mens-chest",
        name: "Men's Chest Wax",
        tagline: "Smooth chest, lasting results.",
        description: "Full chest waxing for a clean, defined look. Longer-lasting than shaving with less irritation over time.",
        priceCash: 55,
        priceCard: 58,
        duration: "30–40 min",
      },
      {
        id: "mens-back-chest",
        name: "Men's Back & Chest Wax",
        tagline: "The complete package.",
        description: "Combine back and chest waxing in one appointment for maximum convenience and savings.",
        priceCash: 105,
        priceCard: 110,
        duration: "60–75 min",
      },
      {
        id: "mens-brow",
        name: "Men's Brow Wax",
        tagline: "Groomed brows, clean look.",
        description: "Clean up the brow line and remove unwanted hair between the brows for a polished, natural look.",
        priceCash: 18,
        priceCard: 19,
        duration: "15 min",
      },
      {
        id: "mens-nose",
        name: "Men's Nose Wax",
        tagline: "Quick, clean, effective.",
        description: "Safe, quick nose wax that removes visible nasal hair. One of our most popular men's services.",
        priceCash: 15,
        priceCard: 16,
        duration: "10 min",
      },
      {
        id: "mens-ear",
        name: "Men's Ear Wax",
        tagline: "Discreet and effective.",
        description: "Removes unwanted ear hair quickly and cleanly.",
        priceCash: 15,
        priceCard: 16,
        duration: "10 min",
      },
    ],
  },
  {
    id: "face",
    name: "Face Waxing",
    description: "Precise facial waxing for perfectly shaped brows, clean upper lips, and smooth skin.",
    icon: "◇",
    services: [
      {
        id: "brow-wax",
        name: "Brow Wax",
        tagline: "Your best brows. Every time.",
        description: "Our brow wax shapes, defines, and cleans up your brows for a polished, natural look. Our estheticians work with your natural brow shape to enhance — never over-thin.",
        whoItsFor: "Anyone who wants clean, defined brows without the guesswork of at-home tweezing.",
        prep: "Come in with your natural brows — no need to shape them beforehand.",
        aftercare: "Avoid touching the area. Apply a gentle moisturizer if needed. Avoid sun exposure for 24 hours.",
        priceCash: 18,
        priceCard: 19,
        duration: "15–20 min",
        popular: true,
      },
      {
        id: "brow-tint",
        name: "Brow Wax + Tint",
        tagline: "Shape and color in one appointment.",
        description: "Combine a precise brow wax with a professional tint to add depth, definition, and fullness to your brows.",
        priceCash: 35,
        priceCard: 37,
        duration: "30 min",
        popular: true,
      },
      {
        id: "upper-lip",
        name: "Upper Lip Wax",
        tagline: "Quick, clean, and effective.",
        description: "A fast, precise upper lip wax that removes unwanted hair and leaves skin smooth. One of our most popular quick services.",
        priceCash: 12,
        priceCard: 13,
        duration: "10 min",
        popular: true,
      },
      {
        id: "chin",
        name: "Chin Wax",
        tagline: "Clean chin, smooth confidence.",
        description: "Removes unwanted chin hair for a clean, smooth finish.",
        priceCash: 12,
        priceCard: 13,
        duration: "10 min",
      },
      {
        id: "full-face",
        name: "Full Face Wax",
        tagline: "Complete facial waxing in one visit.",
        description: "Includes brows, upper lip, chin, cheeks, and sideburns. The complete facial waxing experience.",
        priceCash: 55,
        priceCard: 58,
        duration: "40–50 min",
      },
      {
        id: "cheeks-sideburns",
        name: "Cheeks & Sideburns",
        tagline: "Clean sides, polished look.",
        description: "Removes peach fuzz and unwanted hair from the cheeks and sideburn area.",
        priceCash: 18,
        priceCard: 19,
        duration: "15 min",
      },
    ],
  },
  {
    id: "tinting",
    name: "Tinting",
    description: "Professional brow and lash tinting to enhance your natural features.",
    icon: "◈",
    services: [
      {
        id: "lash-tint",
        name: "Lash Tint",
        tagline: "Defined lashes without the mascara.",
        description: "Professional lash tinting adds depth and definition to your natural lashes. Wake up with beautiful lashes every day.",
        priceCash: 28,
        priceCard: 30,
        duration: "20–25 min",
      },
      {
        id: "brow-tint-only",
        name: "Brow Tint",
        tagline: "Fuller, defined brows.",
        description: "Professional brow tinting to add color, depth, and definition. Great for sparse or light brows.",
        priceCash: 20,
        priceCard: 21,
        duration: "15–20 min",
      },
      {
        id: "lash-brow-tint",
        name: "Lash + Brow Tint",
        tagline: "Complete eye definition.",
        description: "Combine lash and brow tinting in one appointment for a complete, polished eye look.",
        priceCash: 45,
        priceCard: 47,
        duration: "35–40 min",
      },
    ],
  },
];

export const faqs = [
  {
    id: 1,
    category: "First Visit",
    question: "I've never been waxed before. What should I expect?",
    answer: "Welcome! First-time waxing is completely normal, and our estheticians are experienced at making new clients feel at ease. You'll be taken to a private room, given a moment to prepare, and your esthetician will walk you through every step before they begin. Most clients are surprised by how manageable the experience is — especially when they return regularly.",
  },
  {
    id: 2,
    category: "First Visit",
    question: "Is it embarrassing to get a Brazilian wax?",
    answer: "Not at all — and we hear this question often. Our estheticians are licensed professionals who perform these services every day. To them, it's simply their craft. You'll be treated with complete respect and discretion. Many clients who were nervous before their first visit become regulars because of how comfortable the experience actually is.",
  },
  {
    id: 3,
    category: "Preparation",
    question: "How long does my hair need to be?",
    answer: "Hair should be at least ¼ inch long — roughly 3–4 weeks of growth after shaving. If it's too short, the wax won't grip properly. If it's longer than ½ inch, we may trim it before waxing. When in doubt, let it grow a bit more than you think you need.",
  },
  {
    id: 4,
    category: "Preparation",
    question: "Should I do anything to prepare for my appointment?",
    answer: "Yes! Gently exfoliate the area 24–48 hours before your appointment to remove dead skin cells. Avoid applying lotion or oils on the day of your appointment. Wear comfortable, loose-fitting clothing. For bikini/Brazilian services, avoid scheduling during your menstrual cycle if possible, as sensitivity is heightened.",
  },
  {
    id: 5,
    category: "Pain & Comfort",
    question: "Does waxing hurt?",
    answer: "There is some discomfort — we won't pretend otherwise. But most clients describe it as a quick, sharp sensation that passes immediately. The good news: it gets significantly easier with each visit as hair grows back finer and sparser. Regular clients often say their appointments feel much more comfortable than their first experience.",
  },
  {
    id: 6,
    category: "Pain & Comfort",
    question: "How can I reduce discomfort?",
    answer: "Take an over-the-counter pain reliever (like ibuprofen) 30–45 minutes before your appointment. Avoid caffeine on the day of your visit. Make sure your skin is clean and dry. Breathe steadily during the service — our estheticians will often guide your breathing. And remember: it gets easier every time.",
  },
  {
    id: 7,
    category: "Aftercare",
    question: "What should I do after my wax?",
    answer: "For the first 24–48 hours: avoid hot showers, saunas, and steam rooms; skip tight clothing; avoid sun exposure on waxed areas; and hold off on exercise that causes heavy sweating. After 48 hours, begin gentle exfoliation 2–3 times per week to prevent ingrown hairs. Moisturize daily with a fragrance-free lotion.",
  },
  {
    id: 8,
    category: "Aftercare",
    question: "How do I prevent ingrown hairs?",
    answer: "Regular exfoliation is the key. Starting 48 hours after your wax, gently exfoliate the waxed area 2–3 times per week using a soft scrub or exfoliating mitt. Moisturize daily. Wearing loose, breathable clothing also helps. With regular waxing appointments, ingrown hairs typically become less of an issue over time.",
  },
  {
    id: 9,
    category: "Results",
    question: "How long will my results last?",
    answer: "Most clients enjoy smooth skin for 3–6 weeks, depending on their individual hair growth cycle. With regular waxing, hair grows back finer and sparser over time, which means longer-lasting results. We recommend booking your next appointment before you leave to maintain your results.",
  },
  {
    id: 10,
    category: "Booking",
    question: "How do I book an appointment?",
    answer: "You can book online through our booking system — just click 'Book Now' and select your location, service, and preferred time. You can also call your nearest location directly. We recommend booking in advance, especially for weekend appointments.",
  },
  {
    id: 11,
    category: "Booking",
    question: "What is your cancellation policy?",
    answer: "We ask for at least 24 hours notice for cancellations or rescheduling. Late cancellations or no-shows may be subject to a fee. We understand that life happens — just reach out as soon as possible and we'll do our best to accommodate you.",
  },
  {
    id: 12,
    category: "Sanitation",
    question: "How do you ensure sanitation and hygiene?",
    answer: "Sanitation is a non-negotiable standard at Wax Me Too. We use fresh, single-use applicators for every client — no double-dipping, ever. Treatment rooms are thoroughly cleaned and sanitized between every appointment. All linens are changed between clients. Our estheticians follow strict hand hygiene protocols. We use eco-friendly, skin-safe wax products.",
  },
  {
    id: 13,
    category: "Pricing",
    question: "Do you charge more for credit cards?",
    answer: "We display both cash and credit card pricing on our menu. The cash price reflects a small discount for clients who pay with cash. Both prices are clearly listed so you can choose what works best for you.",
  },
  {
    id: 14,
    category: "First Visit",
    question: "Do you offer a new client special?",
    answer: "Yes! We offer a special discount for first-time clients. Ask about our current new client offer when you book, or look for the offer on our homepage. It's our way of welcoming you to the Wax Me Too family.",
  },
];

export const blogPosts = [
  // ── 2024 ──────────────────────────────────────────────────────────────────
  {
    id: "win-complimentary-bikini-wax-summer",
    title: "Win a Complimentary Bikini Wax — Be Smooth and Groovin' Just in Time for Summer!",
    category: "Promotions",
    date: "April 2, 2024",
    excerpt: "Say goodbye to razor burns and hello to silky-smooth skin this summer. Wax Me Too is giving away a complimentary bikini wax — find out how to enter and why waxing is the ultimate summer upgrade.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    slug: "win-complimentary-bikini-wax-summer",
    relatedService: "/services#bikini",
  },
  {
    id: "st-george-premier-waxing-salon",
    title: "Waxing Wonderland: Unveiling St. George's Premier Waxing Salon",
    category: "Locations",
    date: "March 26, 2024",
    excerpt: "From our roots in Draper in 2007 to St. George in 2008, Wax Me Too has been Southern Utah's go-to waxing studio for over 15 years. Discover what makes our St. George location — and our London Brow Company products — truly special.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "st-george-premier-waxing-salon",
    relatedService: "/services#brows",
  },
  {
    id: "vacation-waxing-prep-guide",
    title: "Vacation Baby! How to Prepare for Your Winter Escape with Wax Me Too",
    category: "Prep & Care",
    date: "March 19, 2024",
    excerpt: "Sunscreen — check. Sunglasses — check. Razor? Throw that away. Here's everything you need to know about pre-vacation waxing: timing, what to ask your salon, and why a Brazilian wax is the ultimate travel essential.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    slug: "vacation-waxing-prep-guide",
    relatedService: "/services#bikini",
  },
  {
    id: "military-discounts-wax-me-too-layton",
    title: "Saluting Service: Honoring Our Military with Discounts at Wax Me Too Layton",
    category: "Community",
    date: "March 12, 2024",
    excerpt: "At our Layton studio near Hill AFB, we proudly offer military discounts as a small token of appreciation for those who serve. Meet Liz — retired Air Force Master Sergeant turned waxing expert — and learn how we honor our military community.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "military-discounts-wax-me-too-layton",
    relatedService: "/services",
  },
  {
    id: "why-waxing-is-best-hair-removal",
    title: "Smooth Silhouettes: Why Waxing Is the Best Hair Removal Method",
    category: "Education",
    date: "March 19, 2024",
    excerpt: "In the world of hair removal, waxing stands apart. From longer-lasting results to finer regrowth over time, here's a comprehensive guide to why professional waxing — especially the Brazilian — is the gold standard for smooth skin.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "why-waxing-is-best-hair-removal",
    relatedService: "/services#brazilian",
  },
  {
    id: "bridal-waxing-guide",
    title: "A Bridal Must-Do: The Importance of Pre-Wedding Waxing from Brows to Toes",
    category: "Bridal",
    date: "March 14, 2024",
    excerpt: "Your wedding day deserves flawless skin from head to toe. Utah brides trust Wax Me Too for pre-wedding waxing — here's why we recommend starting at least 3 sessions before the big day, and what to expect.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "bridal-waxing-guide",
    relatedService: "/services#bridal",
  },
  {
    id: "south-jordan-waxing-salon-relocation",
    title: "Smooth Moves: Wax Me Too South Jordan Relocates to a Better Space",
    category: "Locations",
    date: "March 5, 2024",
    excerpt: "We're excited to announce our South Jordan studio has moved to a beautiful new location at 3674 W South Jordan Pkwy. Two full treatment rooms, the same expert estheticians, and all the reasons that make Wax Me Too Utah's most trusted waxing studio.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "south-jordan-waxing-salon-relocation",
    relatedService: "/services#brazilian",
  },

  // ── 2020 ──────────────────────────────────────────────────────────────────
  {
    id: "south-jordan-6th-location-opening",
    title: "Why Wax Me Too South Jordan Is Different from Every Other Waxing Salon",
    category: "Locations",
    date: "February 8, 2020",
    excerpt: "Our 6th Utah location is open in South Jordan — and it comes with 8 reasons why Wax Me Too is unlike any other waxing salon in the state. Local, female-owned, no memberships, and sinks in every room.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "south-jordan-6th-location-opening",
    relatedService: "/services#brazilian",
  },
  {
    id: "free-bikini-wax-layton-utah",
    title: "Waxing in Layton Utah: Enter to Win a Free Bikini Wax at Wax Me Too",
    category: "Promotions",
    date: "February 6, 2020",
    excerpt: "Did you know Wax Me Too gives away a free bikini wax every week? Our Layton studio at 360 Fort Lane is Utah's premier waxing destination — here's how to enter and what makes our Layton team exceptional.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "free-bikini-wax-layton-utah",
    relatedService: "/services#bikini",
  },
  {
    id: "wax-me-too-difference-local-salon",
    title: "The Wax Me Too Difference: Why Utah's Local Waxing Studio Beats Every Chain",
    category: "Education",
    date: "February 5, 2020",
    excerpt: "What separates Wax Me Too from every other waxing salon in Utah? We're local, women-owned, never franchise-backed, and we've never raised our prices. Here's everything that makes us Utah's first and most trusted waxing-only studio.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "wax-me-too-difference-local-salon",
    relatedService: "/services",
  },

  // ── 2019 ──────────────────────────────────────────────────────────────────
  {
    id: "summer-waxing-utah-guide",
    title: "Summer Waxing in Utah: Your Complete Guide to Staying Smooth All Season",
    category: "Prep & Care",
    date: "July 17, 2019",
    excerpt: "Bikinis, lake days, and poolside lounging — summer in Utah is the best reason to ditch the razor for good. Here's everything you need to know about summer waxing, from Brazilian to full leg, at Wax Me Too's 6 Utah locations.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    slug: "summer-waxing-utah-guide",
    relatedService: "/services#bikini",
  },
  {
    id: "first-brazilian-wax-step-by-step",
    title: "Everything You Need to Know Before Your First Brazilian Wax at Wax Me Too",
    category: "Education",
    date: "February 8, 2019",
    excerpt: "Nervous about your first Brazilian wax? We walk you through every step — from the consent form to the cleanup — so you know exactly what to expect at one of our 6 Utah studios. Spoiler: it's easier than you think.",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "first-brazilian-wax-step-by-step",
    relatedService: "/services#brazilian",
  },

  // ── 2017 ──────────────────────────────────────────────────────────────────
  {
    id: "spring-adventure-waxing-utah",
    title: "Adventure's Calling: Get Waxed and Ready for Utah's Best Outdoor Season",
    category: "Lifestyle",
    date: "March 19, 2017",
    excerpt: "Utah's spring and summer are made for adventure — hiking, camping, lake days, and everything in between. Here's why waxing is the smartest prep move before any outdoor adventure, and how monthly waxing creates finer, softer regrowth over time.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
    slug: "spring-adventure-waxing-utah",
    relatedService: "/services#bikini",
  },
  {
    id: "south-jordan-waxing-grand-opening",
    title: "Wax Me Too Opens in South Jordan: Utah's 6th Waxing-Only Studio Is Here",
    category: "Locations",
    date: "March 6, 2017",
    excerpt: "South Jordan, Utah — we've arrived! Wax Me Too's 6th location is now open at South Jordan Parkway, bringing the state's most trusted Brazilian waxing experience to the southwest valley. No memberships, no pressure, just great waxes.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "south-jordan-waxing-grand-opening",
    relatedService: "/services#brazilian",
  },
  {
    id: "waxing-south-jordan-utah-opening",
    title: "Waxing in South Jordan Utah: What to Know Before Your First Appointment",
    category: "Locations",
    date: "March 1, 2017",
    excerpt: "Wax Me Too is opening its doors in South Jordan at the busy crossroads of South Jordan Parkway and Bangerter. Here's everything new clients need to know — including how to prep for a Brazilian wax and why we're different from every other salon.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "waxing-south-jordan-utah-opening",
    relatedService: "/services#brazilian",
  },
  {
    id: "valentines-day-waxing-rippp-and-swear",
    title: "Ripp & Swear: The Things We Do for Love — Valentine's Day Waxing at Wax Me Too",
    category: "Lifestyle",
    date: "February 7, 2017",
    excerpt: "Valentine's Day is the most popular waxing week of the year — and for good reason. Whether you're getting your brows shaped for the big proposal or going full Brazilian for your special evening, Wax Me Too has you covered.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "valentines-day-waxing-rippp-and-swear",
    relatedService: "/services#brows",
  },
  {
    id: "valentines-day-free-wax-giveaway-2017",
    title: "The Best Valentine's Day Gift Ever: Win a Free Wax at Wax Me Too",
    category: "Promotions",
    date: "January 31, 2017",
    excerpt: "What's the perfect Valentine's Day gift — unisex, intimate, and genuinely useful? A Brazilian wax. Enter our weekly free wax drawing and treat yourself (or your partner) to the smoothest Valentine's Day ever.",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "valentines-day-free-wax-giveaway-2017",
    relatedService: "/services#brazilian",
  },
  {
    id: "sundance-film-festival-waxing-utah",
    title: "Utah Snowbunnies, Sundance Film Festival & Brazilian Waxing: How They All Connect",
    category: "Lifestyle",
    date: "January 25, 2017",
    excerpt: "Every January, Hollywood comes to Utah for Sundance — and our phone rings off the hook. Whether you're a local heading to Park City or a visitor from LA, here's why waxing is the ultimate pre-Sundance prep ritual.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1551524164-687a55dd1126?w=600&q=80",
    slug: "sundance-film-festival-waxing-utah",
    relatedService: "/services#brazilian",
  },

  // ── 2016 ──────────────────────────────────────────────────────────────────
  {
    id: "layton-waxing-salon-new-team",
    title: "New! Layton Ladies Go Crazy Over Brazilian Waxing at Wax Me Too",
    category: "Locations",
    date: "December 16, 2016",
    excerpt: "Our Layton studio at 360 Fort Lane has grown to 5 licensed estheticians and 3 full treatment rooms — and the reviews are in. Over 289 five-star ratings and counting. Here's what makes our Layton team the best in Davis County.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "layton-waxing-salon-new-team",
    relatedService: "/services#brazilian",
  },
  {
    id: "pre-vacation-waxing-checklist",
    title: "Don't Hit the Beach Without This Pre-Vacation Waxing Checklist",
    category: "Prep & Care",
    date: "December 14, 2016",
    excerpt: "Heading somewhere warm this winter? Your vacation prep list isn't complete without a wax. Here's the exact timing, what to expect, and why waxing beats shaving every time when you're packing for the beach.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    slug: "pre-vacation-waxing-checklist",
    relatedService: "/services#bikini",
  },
  {
    id: "free-bikini-wax-drawing-utah",
    title: "Are You a Winner? Enter Wax Me Too's Free Bikini Wax Drawing",
    category: "Promotions",
    date: "December 8, 2016",
    excerpt: "Every week, Wax Me Too gives away a free bikini wax to one lucky winner across our 5 Utah locations. Here's how to enter — and why thousands of Utah women trust us for their monthly waxing routine.",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "free-bikini-wax-drawing-utah",
    relatedService: "/services#bikini",
  },
  {
    id: "holiday-waxing-on-top-of-the-world",
    title: "On Top of the World Because of Some Lady Bits: Holiday Waxing at Wax Me Too",
    category: "Lifestyle",
    date: "November 30, 2016",
    excerpt: "The holidays are hectic — but a 15-minute Brazilian wax can make even the most exhausted mom feel amazing. Here's why self-care during the holiday season matters, and how Wax Me Too makes it easy.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "holiday-waxing-on-top-of-the-world",
    relatedService: "/services#brazilian",
  },
  {
    id: "3-worst-things-waxing-salon",
    title: "The 3 Worst Things You Can See in a Waxing Salon (And What to Look For Instead)",
    category: "Education",
    date: "November 18, 2016",
    excerpt: "A dirty sink. A messy workstation. An unhappy esthetician. These are the three biggest red flags in any waxing salon — and why Wax Me Too's strict sanitation standards have made us Utah's most trusted waxing studio since 2007.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "3-worst-things-waxing-salon",
    relatedService: "/services",
  },
  {
    id: "underarm-waxing-guide-utah",
    title: "Harry Pitts: Everything You Need to Know About Underarm Waxing",
    category: "Education",
    date: "November 15, 2016",
    excerpt: "Underarm waxing is one of the most underrated services at Wax Me Too. It takes just 10 minutes, lasts 3–4 weeks, and leaves your underarms smoother than any razor ever could. Here's exactly what to expect.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "underarm-waxing-guide-utah",
    relatedService: "/services#body",
  },
  {
    id: "throw-away-your-razor",
    title: "Throw That Sucker Away: 7 Reasons to Switch from Shaving to Waxing Today",
    category: "Education",
    date: "November 11, 2016",
    excerpt: "Razor burn, stubble, nicks, and hair that grows back thicker — shaving is the worst. Here are 7 compelling reasons to throw away your razor and switch to professional waxing at Wax Me Too.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "throw-away-your-razor",
    relatedService: "/services#legs",
  },
  {
    id: "bikini-wax-types-explained",
    title: "Brazilian vs. Deep Bikini vs. Bikini Wax: Which One Is Right for You?",
    category: "Education",
    date: "November 3, 2016",
    excerpt: "Not sure which bikini wax to book? We break down the differences between a Brazilian, Deep Bikini, and standard Bikini wax — so you can walk into your appointment knowing exactly what you want.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "bikini-wax-types-explained",
    relatedService: "/services#bikini",
  },
  {
    id: "naked-and-afraid-first-brazilian",
    title: "Naked and Afraid: The Real Truth About Getting Your First Brazilian Wax",
    category: "Education",
    date: "November 1, 2016",
    excerpt: "Being naked in front of a stranger, the pain, the embarrassing positions — these are the fears that keep first-timers away from their first Brazilian wax. Here's the honest truth about all of them, from Wax Me Too's expert estheticians.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "naked-and-afraid-first-brazilian",
    relatedService: "/services#brazilian",
  },
  {
    id: "mens-eyebrow-waxing-metrosexual",
    title: "The Metrosexual Male and Eyebrow Waxing: Why Men Are Flocking to Wax Me Too",
    category: "Men's Waxing",
    date: "October 17, 2016",
    excerpt: "The unibrow is out. A clean, masculine brow shape is in. Men's waxing — from brow grooming to the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's everything men need to know before their first appointment.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=600&q=80",
    slug: "mens-eyebrow-waxing-metrosexual",
    relatedService: "/services#mens",
  },
  {
    id: "eyebrow-design-waxing-guide",
    title: "Eyebrow Design: How to Get the Best Brows of Your Life at Wax Me Too",
    category: "Education",
    date: "October 1, 2016",
    excerpt: "At Wax Me Too, we don't just wax brows — we design them. From consultation to tweezers to tiny scissors, here's the full process behind our eyebrow design service and why clients drive from across Utah for their brow appointments.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "eyebrow-design-waxing-guide",
    relatedService: "/services#brows",
  },
  {
    id: "hair-removal-layton-utah",
    title: "Hair Removal in Layton Utah: Meet the Wax Me Too Team at 360 Fort Lane",
    category: "Locations",
    date: "September 28, 2016",
    excerpt: "Our Layton studio has grown from a one-woman operation to a full team of 5 licensed waxing specialists in a beautiful stand-alone space just off Layton Parkway. Here's why North Utah County clients make Wax Me Too their monthly destination.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "hair-removal-layton-utah",
    relatedService: "/services#brazilian",
  },
  {
    id: "brazilian-waxing-salon-qa",
    title: "Brazilian Waxing Salon Q&A: Your Most Common Questions Answered",
    category: "Education",
    date: "October 19, 2016",
    excerpt: "How do I choose the right waxing salon? What should I look for in a treatment room? How do I prepare for my first Brazilian? We answer the most common questions we hear from new clients at Wax Me Too.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "brazilian-waxing-salon-qa",
    relatedService: "/services#brazilian",
  },

  // ── 2015 ──────────────────────────────────────────────────────────────────
  {
    id: "prevention-magazine-bikini-wax-tips",
    title: "Wax Me Too Featured in Prevention Magazine: 9 Tips for the Perfect Bikini Wax",
    category: "Press",
    date: "March 28, 2015",
    excerpt: "Prevention Magazine called us — one of America's leading health and beauty publications — to get our expert tips on getting the perfect bikini wax. Here's what co-founder Jolie Arsenault shared with millions of readers.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "prevention-magazine-bikini-wax-tips",
    relatedService: "/services#bikini",
  },
  {
    id: "layton-waxing-milly-speaks-spanish",
    title: "Brazilian Waxing in Layton Utah with Milly — Ella Habla Español",
    category: "Locations",
    date: "March 4, 2015",
    excerpt: "Meet Milly — our newest Layton esthetician with 20 years of experience, originally from Venezuela, and fluent in Spanish. Wax Me Too Layton is proud to serve our Spanish-speaking community at our beautiful new 360 Fort Lane location.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "layton-waxing-milly-speaks-spanish",
    relatedService: "/services#brazilian",
  },
  {
    id: "valentines-day-brazilian-wax-gift",
    title: "The Perfect Valentine's Day Gift: Why a Brazilian Wax Is the Ultimate Romantic Treat",
    category: "Lifestyle",
    date: "January 26, 2015",
    excerpt: "Looking for a Valentine's Day gift that's unisex, intimate, and genuinely useful? The Brazilian wax is the answer. Here's why thousands of Utah couples make Wax Me Too their Valentine's Day tradition — and how to prepare.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "valentines-day-brazilian-wax-gift",
    relatedService: "/services#brazilian",
  },
  {
    id: "layton-waxing-salon-new-location",
    title: "Wax Me Too Layton Has Moved to a Beautiful New Salon at Fort Lane Plaza",
    category: "Locations",
    date: "January 10, 2015",
    excerpt: "After 4 years of outgrowing our old space, Wax Me Too Layton has moved to a stunning new studio at 360 Fort Lane. Fresh paint, new flooring, sinks in every room, and the same expert team you've trusted for years.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "layton-waxing-salon-new-location",
    relatedService: "/services#brazilian",
  },

  // ── 2013 ──────────────────────────────────────────────────────────────────
  {
    id: "15-minute-brazilian-wax-experience",
    title: "The 15-Minute Brazilian Wax: What Really Happens Inside a Wax Me Too Studio",
    category: "Education",
    date: "November 7, 2013",
    excerpt: "Fifteen minutes. That's all it takes for a complete Brazilian wax at Wax Me Too. Here's a candid, behind-the-scenes look at what really happens during your appointment — and why our clients keep coming back every month.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "15-minute-brazilian-wax-experience",
    relatedService: "/services#brazilian",
  },
  {
    id: "draper-waxing-salon-expansion",
    title: "Wax Me Too Draper Expands: A Fourth Treatment Room Opens Due to High Demand",
    category: "Locations",
    date: "July 31, 2013",
    excerpt: "Due to overwhelming demand, our Draper studio inside Image Studios has opened its fourth treatment room. Owner Joann Gibb shares what drives the summer surge in waxing appointments — and why once clients start, they rarely stop.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "draper-waxing-salon-expansion",
    relatedService: "/services#brazilian",
  },
  {
    id: "salt-lake-city-waxing-salon",
    title: "Brazilian Waxing in Salt Lake City: Inside Wax Me Too's Downtown Studio",
    category: "Locations",
    date: "April 5, 2013",
    excerpt: "Our downtown Salt Lake City studio is one of our busiest — and for good reason. 3 treatment rooms, 7 expert waxers, and hours from early morning to late evening. Here's what makes our SLC location the go-to for waxing in the city.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "salt-lake-city-waxing-salon",
    relatedService: "/services#brazilian",
  },
  {
    id: "valentines-day-free-brazilian-2013",
    title: "Win a Free Brazilian Wax for Valentine's Day 2013 at Wax Me Too",
    category: "Promotions",
    date: "January 28, 2013",
    excerpt: "In honor of Valentine's Day 2013, Wax Me Too is giving away a free Brazilian wax to one lucky winner. Here's how to enter — and why the Brazilian wax is the most romantic gift you can give (or receive) this February.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "valentines-day-free-brazilian-2013",
    relatedService: "/services#brazilian",
  },

  // ── 2012 ──────────────────────────────────────────────────────────────────
  {
    id: "utah-waxing-salon-established-2007",
    title: "Utah's First Waxing-Only Salon: The Story Behind Wax Me Too",
    category: "About",
    date: "December 15, 2012",
    excerpt: "In 2007, two best friends saw a gap in Utah's beauty market and opened the state's first waxing-only salon. Here's the story of how Wax Me Too was born, what drives our philosophy, and why we've grown to 6 locations across Utah.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "utah-waxing-salon-established-2007",
    relatedService: "/services",
  },
  {
    id: "brazilian-wax-benefits-vs-shaving",
    title: "Brazilian Wax vs. Shaving: Why Waxing Wins Every Time",
    category: "Education",
    date: "November 10, 2012",
    excerpt: "Shaving leaves stubble, ingrown hairs, and razor burn. Waxing removes hair from the root, leaving skin smooth for weeks and causing hair to grow back finer over time. Here's the complete comparison — and why Wax Me Too clients never go back to shaving.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "brazilian-wax-benefits-vs-shaving",
    relatedService: "/services#brazilian",
  },
  {
    id: "waxing-while-pregnant-utah",
    title: "Can You Wax While Pregnant? Everything Expecting Moms Need to Know",
    category: "Education",
    date: "October 5, 2012",
    excerpt: "Yes, you can wax while pregnant — with a few important considerations. Our licensed estheticians at Wax Me Too have helped hundreds of expecting moms stay smooth and comfortable throughout their pregnancies. Here's what you need to know.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=80",
    slug: "waxing-while-pregnant-utah",
    relatedService: "/services#brazilian",
  },
  {
    id: "ingrown-hair-prevention-waxing",
    title: "Ingrown Hairs After Waxing: How to Prevent Them and Keep Skin Smooth",
    category: "Prep & Care",
    date: "September 12, 2012",
    excerpt: "Ingrown hairs are one of the most common concerns after waxing — but they're largely preventable. Here's our expert guide to exfoliation, moisturizing, and aftercare that keeps skin smooth and bump-free between appointments.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "ingrown-hair-prevention-waxing",
    relatedService: "/after-care",
  },
  {
    id: "waxing-sensitive-skin-guide",
    title: "Waxing with Sensitive Skin: Tips from Wax Me Too's Expert Estheticians",
    category: "Education",
    date: "August 20, 2012",
    excerpt: "Sensitive skin doesn't have to mean painful waxing. Our estheticians use fragrance-free honey wax and gentle techniques specifically designed for reactive skin types. Here's how we make waxing comfortable for everyone.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "waxing-sensitive-skin-guide",
    relatedService: "/services#brazilian",
  },
  {
    id: "how-often-should-you-wax",
    title: "How Often Should You Wax? The Complete Guide to Waxing Frequency",
    category: "Education",
    date: "July 15, 2012",
    excerpt: "Most clients wax every 4 weeks — but the right frequency depends on your hair growth cycle, the area being waxed, and your personal preference. Here's the complete guide from Wax Me Too's licensed estheticians.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "how-often-should-you-wax",
    relatedService: "/services",
  },
  {
    id: "waxing-for-men-manzilian-guide",
    title: "Men's Waxing Guide: Everything You Need to Know About the Manzilian",
    category: "Men's Waxing",
    date: "June 10, 2012",
    excerpt: "Men's waxing — especially the Manzilian — is one of the fastest-growing services at Wax Me Too. Here's a complete guide for men considering their first appointment: what to expect, how to prepare, and why it's worth it.",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?w=600&q=80",
    slug: "waxing-for-men-manzilian-guide",
    relatedService: "/services#mens",
  },
  {
    id: "st-george-waxing-salon-utah",
    title: "Waxing in St. George Utah: Wax Me Too's Southern Utah Studio",
    category: "Locations",
    date: "May 5, 2012",
    excerpt: "Wax Me Too's St. George studio was our second location ever — and it's been serving Southern Utah and Mesquite, Nevada clients since 2008. Here's what makes our St. George team special and why clients drive from across Washington County to see us.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
    slug: "st-george-waxing-salon-utah",
    relatedService: "/services#brazilian",
  },
  {
    id: "waxing-aftercare-guide",
    title: "Waxing Aftercare: The Complete Guide to Caring for Your Skin After a Wax",
    category: "Prep & Care",
    date: "April 2, 2012",
    excerpt: "What you do in the 24–48 hours after your wax matters as much as the wax itself. Here's the complete aftercare guide from Wax Me Too — covering what to avoid, how to moisturize, and how to prevent ingrown hairs.",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "waxing-aftercare-guide",
    relatedService: "/after-care",
  },
  {
    id: "waxing-before-care-guide",
    title: "How to Prepare for Your Wax: The Complete Before-Care Guide",
    category: "Prep & Care",
    date: "March 15, 2012",
    excerpt: "The secret to a great wax starts before you even walk in the door. Here's everything you need to do — and avoid — in the days leading up to your appointment to ensure the smoothest, most complete wax possible.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    slug: "waxing-before-care-guide",
    relatedService: "/before-care",
  },
  {
    id: "wax-me-too-happy-faces-community",
    title: "Happy Faces: How Wax Me Too Gives Back to Utah's Youth Through Free Waxing",
    category: "Community",
    date: "February 20, 2012",
    excerpt: "Our Happy Faces program donates free brow and lip waxing to middle and high school students who need a confidence boost. Here's the story behind the program and why giving back to Utah's youth is at the heart of everything we do at Wax Me Too.",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    slug: "wax-me-too-happy-faces-community",
    relatedService: "/about",
  },
  {
    id: "waxing-faq-utah",
    title: "Waxing FAQ: Your Most Common Questions About Professional Waxing Answered",
    category: "Education",
    date: "January 10, 2012",
    excerpt: "Can you wax during your period? How long does hair need to be? Does waxing hurt less over time? We answer the 20 most common questions we hear from new and returning clients at Wax Me Too's Utah studios.",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    slug: "waxing-faq-utah",
    relatedService: "/faq",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    location: "Layton, UT",
    rating: 5,
    text: "I was so nervous for my first Brazilian, but my esthetician made me feel completely at ease. She explained everything, was so professional, and the result was amazing. I'm already booked for next month!",
    service: "Brazilian Wax",
  },
  {
    id: 2,
    name: "Jessica T.",
    location: "Salt Lake City, UT",
    rating: 5,
    text: "I've been coming to Wax Me Too for three years and I won't go anywhere else. The consistency is incredible — every esthetician is skilled, the studios are always immaculate, and I always leave feeling great.",
    service: "Regular Client",
  },
  {
    id: 3,
    name: "Amanda R.",
    location: "Orem, UT",
    rating: 5,
    text: "The brow wax here is genuinely the best I've ever had. They work with your natural shape instead of over-thinning, and the results last so much longer than I expected.",
    service: "Brow Wax",
  },
  {
    id: 4,
    name: "Kayla B.",
    location: "Draper, UT",
    rating: 5,
    text: "As someone who was always self-conscious about getting waxed, I cannot say enough about how comfortable this place makes you feel. Zero judgment, total professionalism, and genuinely great results.",
    service: "Brazilian Wax",
  },
  {
    id: 5,
    name: "Michelle L.",
    location: "Layton, UT",
    rating: 5,
    text: "I switched from shaving to waxing two years ago and I'll never go back. The hair grows back so much finer now, and my appointments are quick and easy. The new client offer made it easy to try.",
    service: "Full Leg + Underarm",
  },
  {
    id: 6,
    name: "Taylor H.",
    location: "Salt Lake City, UT",
    rating: 5,
    text: "Brought my sister for her first wax and we both left raving. The studio is beautiful, the staff is warm and knowledgeable, and the pricing is very fair for the quality you get.",
    service: "First Visit",
  },
];

export const trustBadges = [
  { icon: "🌿", label: "Eco-Friendly Products" },
  { icon: "✦", label: "Women-Owned Since 2007" },
  { icon: "🔒", label: "Privacy-First Standards" },
  { icon: "⭐", label: "500+ 5-Star Reviews" },
  { icon: "🧼", label: "Strict Sanitation Protocols" },
  { icon: "💛", label: "No Double-Dipping, Ever" },
];
